### ISSUE TITLE
Can't load news in China

### ISSUE THREAD

**Issue by KDr2** [dangwu/Octal#1]
I live in China behind the Great Fire Wall. Using this app, I can't load any news but only see many miserable placeholders. But the hack news website is not blocked by the GFW at all. I can load news with any other hack news client app from the app store. If I dial a VPN which can cross the GFW, this app works very well, and I love it UI especially the comment tree.

Also, without a VPN, I can log in, though I can't load any news. That's weird.

Could you consider to fix this, please?

**Comment by dangwu** [comment]
Hello there - I'm sorry to hear that the app doesn't load the news for you in China. Octal uses Hacker News' official API, which uses Google's Firebase SDK. It looks like China currently blocks Firebase, so there's unfortunately nothing I can do here except recommend that you use a VPN.

https://groups.google.com/forum/#!topic/firebase-talk/mkyeTKU839Q

**Comment by KDr2** [comment]
Hmm... OK.
