### ISSUE TITLE
Display article rank

### ISSUE THREAD

**Issue by ishitatsuyuki** [dangwu/Octal#10]
The article rank (index) should be displayed so that it's easier to stop at e.g. top 25 articles.

**Comment by dangwu** [comment]
On it. Will be part of v2.5.0 which will likely be released tomorrow.

**Comment by dangwu** [comment]
Published!

**Comment by ishitatsuyuki** [comment]
I'm lost in the endless list of articles again after the redesign.

Can you add the numbers back?
