### ISSUE TITLE
[Bug] Edit-comment truncation

### ISSUE THREAD

**Issue by teddy-error** [dangwu/Octal#102]
Editing a long comment now shrinks the size of the “textarea” to an extent that editing is impossible

**Comment by dangwu** [comment]
Thanks for the report. I'll look into this.

**Comment by dangwu** [comment]
I have no idea what the issue is yet, but I have discovered that if you press the Return key at the end of the text, it seems to resolves the issue

**Comment by teddy-error** [comment]
Update here: I think it’s an underlying API change as I’ve now noticed the same issue with Apollo.

**Comment by dangwu** [comment]
Good to know. Let's see if Apple fixes it with iOS 13.1 then.
