### ISSUE TITLE
[Bug] URLs in comments should open on TouchUp gesture (rather than TouchDown)

### ISSUE THREAD

**Issue by zx8** [dangwu/Octal#103]
I'm not sure if this behaviour recently changed, but I'm using v3.9.0 and URLs included in comments seem to be opening as soon as I tap them, rather than after I release my finger from the screen. This is undesirable for two reasons:

1. I can no longer "tap and hold" to copy the link
2. I keep accidentally tapping and opening external links while trying to scroll through comments

Could you possibly revert back to the old behaviour of opening URLs inside comments on TouchUp rather than TouchDown? I'm sure this used to be the behaviour and am not sure when exactly it changed.

**Comment by dangwu** [comment]
I haven't recently changed this code at all. Must have changed with iOS 13. I'll look into it!

**Comment by luckman212** [comment]
I came to report the same thing... yes this seems to be some sort of iOS13 specific problem.

FWIW  I am on an iPhoneXS w/ iOS 13.1 final.

**Comment by dangwu** [comment]
Found the issue. Fixing in the next release!

**Comment by dangwu** [comment]
Fix is out with 3.10.0
