### ISSUE TITLE
[Feature] Add an alternate dark home screen icon

### ISSUE THREAD

**Issue by ryanmcgrath** [dangwu/Octal#104]
Hey-o,

Would be cool if more apps supported a dark-mode icon ala https://developer.apple.com/documentation/uikit/uiapplication/2806815-supportsalternateicons

Any thoughts on doing so? Yours is pretty straightforward I think, just invert the white background.

Cheers!

**Comment by dangwu** [comment]
Not a bad idea. Will get to this when I get time.

**Comment by dangwu** [comment]
This is coming (as soon as Apple approves the submission) for Premium users! Let me know if you need a free Premium promo code ;)

**Comment by ryanmcgrath** [comment]
I believe I'm premium already, haha - but I appreciate it! Nice to see this after so long, had figured you'd gotten too busy. Thanks!

**Comment by ryanmcgrath** [comment]
Just a heads up - love the icon! Will go ahead and close this. Thanks again!
