### ISSUE TITLE
[Bug]HTML Entities not rendered in title 

### ISSUE THREAD

**Issue by jxcl** [dangwu/Octal#108]
See top submission of attached image. Title should be rendered `<head>` but instead renders the html entity code. ![425FEC73-42DC-4494-B642-5EF753E725FB](https://user-images.githubusercontent.com/108500/65920532-7a6edd00-e39c-11e9-8c93-dc5d8bc901d0.png)

**Comment by dangwu** [comment]
Yup - fix coming!

**Comment by dangwu** [comment]
Fixed in 3.11.0!
