### ISSUE TITLE
[Bug] Automatic Dark Mode stopped working 

### ISSUE THREAD

**Issue by christianhans** [dangwu/Octal#109]
Octal doesn’t automatically switch between light and dark mode anymore. Restarting the App doesn’t help. I have to go into the App settings and toggle “Use system appearance” to use the right theme.

Not sure what the cause is, it may have been the recent iOS update to 13.1.2. Reeder app had the same problem but that was fixed via an App update today.

**Comment by dangwu** [comment]
I’m not experiencing this issue. Can you provide exact repro steps? A video
would be helpful too.

**Comment by christianhans** [comment]
Sure, here is a video:

https://www.dropbox.com/s/w60egwgmofthyqx/Video%20Oct%2009%2C%2011%2018%2029.mp4?dl=0

**Comment by dangwu** [comment]
Thank you! Super helpful. Found the issue. Fix coming soon.
