### ISSUE TITLE
[Bug] Follow Readable Width for layout margins

### ISSUE THREAD

**Issue by ekoranek12** [dangwu/Octal#11]
The `readableContentGuide` adjusts based on the devices screen size, orientation, and size class to present content in a more visually appealing and digestible way. This guide varies from full screen width on a portrait iPhone to centered and inset on the left and right on the largest iPads. This would be an improvement for the iPad version of the app where all of the content stretches the full width of the screen. 

Depending on your implementation implementing this could be as easy as checking a few boxes in interface builder. I’m happy to provide additional information!

Apple Doc:
https://developer.apple.com/documentation/uikit/uiview/1622644-readablecontentguide

Example Usage:
https://useyourloaf.com/blog/readable-content-guides/

**Comment by ekoranek12** [comment]
Reader mode in safari gives a good example of how content is laid out in different orientations.

**Comment by dangwu** [comment]
Interesting... I wasn't aware of this concept. I was planning to add 2-pane support (e.g. SplitView), which would make the reading width smaller as a side-effect. Would you not prefer that?

**Comment by ekoranek12** [comment]
That works too! I was simply throwing out a low impact solution. I don't want to contradict your planned development path. 

Assuming the 4 article tabs move to split view, this could still be useful for settings. Also, if you include UISplitViewController's [displayModeButtonItem](https://developer.apple.com/documentation/uikit/uisplitviewcontroller/1623196-displaymodebuttonitem) on the detail view controllers you may still want them to follow readable width to layout more nicely when the master view controller is hidden.

**Comment by dangwu** [comment]
Cool, thanks for the suggestions! Will definitely keep that in mind what I get to it.

**Comment by dangwu** [comment]
Added readable width setting on iPads
