### ISSUE TITLE
[Feature] Utilize catalyst to make a Mac app

### ISSUE THREAD

**Issue by kcmannem** [dangwu/Octal#115]
I feel octal could be great Mac app. I often read HN on my computer more than my phone. Even something like a basic port would suffice.

**Comment by pcr910303** [comment]
YMMV, but... [I don’t like Marzipan (and Catalyst)](https://bzamayo.com/marzipan).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kcmannem** [comment]
well its either that or nothing at all

**Comment by zshbleaker** [comment]
Hope to see Octal the Mac. Just reserve a sit for it on my Dock.

**Comment by dangwu** [comment]
Interesting idea but I don’t even have enough bandwidth to handle iPads 🤔

**Comment by pcr910303** [comment]
OK, this sounds like bit of an ad but I'm trying to make a macOS AppKit HN app - https://github.com/pcr910303/HackerNews. You all might want to check it out...

**Comment by dangwu** [comment]
That's super cool dude! Congrats! Do you have an iPad app with the same
code?

**Comment by pcr910303** [comment]
@dangwu No, I'm not trying to make an iOS one - I'm already using Octal 👍 

I have to rewrite the whole app in UIKit if I want to make one - seems unlikely.

**Comment by luckman212** [comment]
Just throwing my hat in the ring:  I absolutely _hate_ Marzipan or whatever it's called. I have a few apps on my Mac that use it - they are ugly and borderline unusable as far as speed, UX etc.

I appreciate the goal of cross platform apps and less work for developers but I'd rather use a Qt app (or an Electron one) than Marzipan any day. It's mostly a toy in its current form.

**Comment by pcr910303** [comment]
@luckman212 I'm surprised you hate Catalyst (the new name of Marzipan) but is fine with Electron or Qt. Both aren't really optimal UX on macOS (compared to Cocoa apps), and I find Catalyst is faster than Electon since it doesn't spin up a new Chrome instance. While Qt is not slow as Electron, it's super ugly, at least for me.

**Comment by luckman212** [comment]
@pcr910303 I hate the memory use and slow startup time of Electron, but once they're warmed up, the experience isn't that bad (VSCode for example).

Can you name a single Marzipan app that doesn't look & feel like a toy? I'm open to a change of opinion, but for now that's been my experience.

**Comment by pcr910303** [comment]
@luckman212 

> I hate the memory use and slow startup time of Electron, but once they're warmed up, the experience isn't that bad (VSCode for example).

That's probably b.c. VSCode optimizes so much for great perf. Try... for example Slack or Messenger. It's terrible. Every time I type anything in Messenger the CPU perf of Messenger Helper.app soars up to 150% 😞 

> Can you name a single Marzipan app that doesn't look & feel like a toy?

Every Catalyst app feels like a toy, that I agree, but at least it has proper drag & drop support / toolbars, etc... For example the Podcasts app bundled in macOS is pretty good considering it's not Cocoa. (Some panels still look like shit though.)

**Comment by zshbleaker** [comment]
@

**Comment by zshbleaker** [comment]
@pcr910303 Vectornator Pro. Still a toy compared to the giant competitors like Adobe Illustrator and OmniGraffle but much better than other Marzipan apps.
