### ISSUE TITLE
[Feature] See own comments & submission points

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#116]
I would like to see my own comments & submission points. 
It is impossible to upvote my own comments & submissions, so there should be some special handling so that

- the upvote button should not be displayed (displaying star much like the HN website will be fine, I think)
- and the points of my own comments should be displayed (maybe next to the star I mentioned?)

**Comment by dangwu** [comment]
Will fix the first bullet point. 

Unfortunately there's no way to obtain your own comment scores through the API.

**Comment by pcr910303** [comment]
@dangwu Oh, and while doing that, can you make my own comments editable?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
They already are editable.

**Comment by pcr910303** [comment]
Hmm, never seen an option... Will try again soon.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
You can’t edit comments past a certain period. I think it’s 30 minutes but
I need to double check.

**Comment by pcr910303** [comment]
Ah, thanks. I  forgot about the limit.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pcr910303** [comment]
@dangwu Looks like I still can vote up my submissions & comments :-(
