### ISSUE TITLE
[Feature] SF Symbol based icons

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#117]
In iOS 13, the general shape of the icons have changed much, and the icons have been published as a font set called [SF Symbols](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/).

The app would look much coherent if it would use SF Symbols on iOS 13 (the most glaring inconsistency is on the comment page, where the sharing icon is round with a iOS 13-esque feel while the bookmarks icon is sharp & thin which goes with an iOS 12 or up-esque feel.

For the bookmarks, there exists the `bookmark` & `bookmark.fill` icons.
![image](https://user-images.githubusercontent.com/37990858/67651992-665fd080-f986-11e9-9a13-f4680d536086.png)

The icon used for upvote is available as `arrow.up.circle` & `arrow.up.circle.fill` icons.
![image](https://user-images.githubusercontent.com/37990858/67652066-ba6ab500-f986-11e9-8880-f78d325e7e53.png)

The icon used for new post is available as `plus.square.fill` and the other `plus.*` icons.
![image](https://user-images.githubusercontent.com/37990858/67652089-d2dacf80-f986-11e9-82b4-e69f9bac1bc4.png)

The icon used as account is available as `person.fill` and the other `person.*` icons.
![image](https://user-images.githubusercontent.com/37990858/67652132-f9990600-f986-11e9-9b27-ab284c4917ae.png)

For the filtering icon, while the currently used preference-style icons don't exist, there exists the `line.horizontal.3.decrease.circle` and `line.horizontal.3.decrease.circle.fill` icons which IMHO conveys the meaning better.
![image](https://user-images.githubusercontent.com/37990858/67652254-64e2d800-f987-11e9-8433-382e0027c77d.png)

The icon used for logout doesn't exist, but the `escape` icon can be used.
![image](https://user-images.githubusercontent.com/37990858/67652371-f2bec300-f987-11e9-8570-a08cfe054311.png)

**Comment by dangwu** [comment]
Very nice. I can switch over to these eventually, but it currently requires iOS13 and I'd like to give users a bit more time to update.

**Comment by dangwu** [comment]
New app update uses SF Symbols for almost everything. I love them, so thanks for the idea!
