### ISSUE TITLE
[Bug] low-contrast text of UISegmentedControl in light mode

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#119]
In light mode, the UISegmentedControl's text for selecting top/best/new is low-contrast.

![IMG_1538](https://user-images.githubusercontent.com/37990858/67725574-349e4680-fa26-11e9-9133-13d52119774a.png)

**Comment by pcr910303** [comment]
I'm not sure whether using another panel for this is a right choice, as there are separate tabs for Ask HN, Show HN, and Jobs (which I never use). It's odd to see these selection separately.

I'm not sure how to 'fix' this, but one idea is a `mail.app` like layout, where there can be many mailboxes which are much more than what the screen can contain.

**Comment by dangwu** [comment]
Good find - will fix.

**Comment by dangwu** [comment]
Fixed!
