### ISSUE TITLE
[Bug] Thumbnail in App Switcher turns from dark to light when switching away from Octal

### ISSUE THREAD

**Issue by SuperTachyon** [dangwu/Octal#120]
When dark mode is enabled, switching away from Octal makes its thumbnail in App Switcher turn light. 

Video https://streamable.com/tw2bu

**Comment by SuperTachyon** [comment]
A Twitter from dev of Twitterific, which might be related. https://twitter.com/BigZaphod/status/1189291703041171461

**Comment by dangwu** [comment]
Strange - good find. I'll look into it when I get time but this is very low priority
