### ISSUE TITLE
[Bug] Post doesn't open through Opener when another one is already open

### ISSUE THREAD

**Issue by nyuszika7h** [dangwu/Octal#121]
# Steps to reproduce
1. Open a post in Octal through Opener
2. Switch to a different app
3. Open another post in Octal through Opener

# Expected beavior
The new post should be opened in Octal.

# Actual behavior
Octal opens but shows the previously opened post.

If I close the post within Octal first, then opening another post through Opener works as expected.

# Details

- **Device**: iPhone XR
- **OS**: iOS 13.2
- **Octal version**: 3.11.2
- **Opener version**: 1.8.1

**Comment by dangwu** [comment]
Good find. Will fix

**Comment by dangwu** [comment]
Should be fixed. Please re-open this issue if it persists.
