### ISSUE TITLE
[Feature] 3D Touch on links

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#123]
I would like if 3D Touch previews work on links (like other apps).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
Apple killed 3D Touch with the iPhone 11. Will be replacing preview with
the new API

**Comment by dangwu** [comment]
Replaced

**Comment by pcr910303** [comment]
@dangwu Sorry for the confusion, I wasn't saying about the items in the main screen: I was mentioning about the URL of the story/URLs mentioned on the comments.

For example, currently trying to long-touching/3D-touching links in comments does nothing, and long-touching links of stories select them (and that's probably not intended behavior, since only the host part of the URL is displayed).

I believe that long touching them should display the contents of the URL.

(BTW, I was too lazy for a while to open new bugs, but I also think that long-pressing the items in the first page should preview the comments or the story's contents, not the table cell itself - which doesn't provide much value to the user.)

**Comment by pcr910303** [comment]
Resolved in 3.16.0. 🎉
