### ISSUE TITLE
Login credentials are not saved

### ISSUE THREAD

**Issue by Victornovikov** [dangwu/Octal#124]
I have to login again and again. 
It is inconvenient and doesn’t allow using some of the key features (bookmarking, upvoting etc.)

**Comment by dangwu** [comment]
Can you try in a web browser?

**Comment by dangwu** [comment]
See this thread:
https://news.ycombinator.com/item?id=21573467

**Comment by Victornovikov** [comment]
Yep, I tried. I don’t have any issues with logging in outside of the application. 
I didn’t have any issues with other apps either..

**Comment by dangwu** [comment]
Strange... do you have any special characters in your password?

**Comment by Victornovikov** [comment]
I have "!" and that's it. 
 I have that issue on both ipad and iphone.
let me know if there is any kind of research you want me to do.
