### ISSUE TITLE
Dark Mode - please bring back!

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#127]
Thanks for the steady updates! (I just noticed the Tip Jar and deposited into it - glad this feature made it in)

I'd like to kindly request bringing back manual control of dark mode. I much prefer reading in Octal in dark mode regardless of the system setting. If not too much trouble, please bring back the ability to manually select a mode.

**Comment by oh-fv** [comment]
I agree, please bring back manual dark mode 👍

**Comment by dangwu** [comment]
Sorry about that. Was hoping to simplify but looks like there’s demand!
Will add an override toggle soon.

**Comment by andrewwu** [comment]
Agreed! I just unlocked premium thinking that the manual toggle was going be enabled. Is there an ETA as to when it’ll be back? Thanks!

**Comment by dangwu** [comment]
Will prioritize. What’s the use case for wanting octal dark while the
system isn’t? (Or vice versa)

**Comment by andrewwu** [comment]
I’m OK with the system’s automatic light/dark mode but for news apps where I spend most of the time reading walls of text, permanent dark mode makes it easier on the eyes.

**Comment by dangwu** [comment]
Adding in next release (this week)

**Comment by dangwu** [comment]
Released

**Comment by luckman212** [comment]
My 👀 thank you
