### ISSUE TITLE
[Bug] Stops before scrolling to top of posts

### ISSUE THREAD

**Issue by chrisellsworth** [dangwu/Octal#129]
I use the tab bar buttons as “home” buttons to scroll to the top of the posts list when foregrounding the app, so that I can then pull to refresh. 

In the following video, I pressed the lower left button a total of three times to get to the top: https://imgur.com/a/lwFxBlI

From what I can tell, this is 100% reproducible if I open Octal, scroll down the posts list a bit, switch to another app, switch back to Octal, and then tap the tab bar button. 

A similar behavior is also apparent if I scroll to the bottom of Settings, switch to posts, then back to Settings. The Settings button must be tapped three times or so to get to the top. 

iPhone 11 Pro / iOS 13.2.3 / Octal 3.14

(By the way, I didn’t see a way to get the current Octal version from within the app, is there such a thing?)

**Comment by dangwu** [comment]
This should be fixed. Re-open if not!
