### ISSUE TITLE
Gray letterboxing on iPad is not scrollable. 

### ISSUE THREAD

**Issue by rupino** [dangwu/Octal#130]
When viewing a list of comments on iPad, there is significant grey letterboxing to the left and right of the comments. Scrolling in this grey area with finger swipe does not work. Please fix so you can swipe the grey area to scroll.

**Comment by SuperTachyon** [comment]
I begin to notice this annoying change as well. I think the letterbox was added to achieve the recommended reading width on iPad. But the letterbox should definitely responses to touch gestures.

**Comment by dangwu** [comment]
Sorry both of you, I’ve been sorry busy. Will fix this ASAP!

**Comment by rupino** [comment]
No worries. Thanks for the reply.

**Comment by dangwu** [comment]
I spent some time on this trying for a quick fix but there's nothing quick. Instead I've added a new setting to disable this letterboxing entirely if you want to. A new version of the app will release tomorrow with this setting. I'll continue to brainstorm a long-term fix for ability to scroll the letterboxing.
