### ISSUE TITLE
Support text-to-speech 

### ISSUE THREAD

**Issue by christefano** [dangwu/Octal#136]
In the comment … menu (screenshot attached), I half-expected “Speak” to be an available option. 

![5C056381-B7F7-45CB-A551-A1E4580ADD84](https://user-images.githubusercontent.com/105058/73893059-6dbc3300-482d-11ea-936e-5e2088ba6027.png)

I’d also love to be able to select text to have it read aloud. I’ve exposed this functionality in other apps through the iOS accessibility settings at Accessibility -> Spoken Content -> Speak Selection

**Comment by dangwu** [comment]
Interesting idea, but I don't want to overload that already crowded menu
with options that 1-2 people would use. What other apps have a feature like
this?

**Comment by christefano** [comment]
> What other apps have a feature like this? 

Facebook’s native app comes to mind.

>> I’d also love to be able to select text to have it read aloud. I’ve exposed this functionality in other apps through the iOS accessibility settings at Accessibility -> Spoken Content -> Speak Selection

Any idea if selecting text in the comments is on the roadmap? This would make it possible to simply select “Speak” in the text selection popup menu.

![FullSizeRender](https://user-images.githubusercontent.com/105058/74184126-10442f80-4bfb-11ea-8ea8-cd3e5c07d5fb.jpg)

**Comment by dangwu** [comment]
Gotcha. Yes I need to fix text selection in comments, especially if that
enables that "Speak" option by default! Selection used to work and
something broke it in iOS13.

**Comment by christefano** [comment]
Excellent, thank you! This would be the ideal UI for me. Makes sense about not cluttering up the menu.

(For anyone tuning in, the “Speak” item doesn’t show up automatically in iOS for some reason. It needs to be enabled at <code>Accessibility</code> -> <code>Spoken Content</code> -> <code>Speak Selection</code>)

**Comment by dangwu** [comment]
Just investigated and comment text selection actually works if you tap and
drag! Try it out - works for me!

**Comment by christefano** [comment]
Hey, it works! I wonder what changed between now and opening the ticket 😅

**Comment by dangwu** [comment]
I might help to disable "Quick Collapse" in the settings. Then you can
double tap any word to quickly begin highlighting it.
