### ISSUE TITLE
[Bug] App reloads every time it gets to the background

### ISSUE THREAD

**Issue by SuperTachyon** [dangwu/Octal#137]
100% reproducible for Octal 3.14.2 on iPadOS 13.3.1

There seems to be some changes on app state restoration in iOS 13. Now Octal will just load the main page after it gets to the background.

**Comment by dangwu** [comment]
I’ll have to look into this! Thanks for the report.

**Comment by SuperTachyon** [comment]
It seems to be related to the new toggle for comment width. When the width is limited, this doesn’t seem to happen.

**Comment by dangwu** [comment]
So strange... been meaning to look into this but been bogged down by my day job. Sorry for the delay

**Comment by dangwu** [comment]
I'm not sure that there's really anything Ic an do to fix this.k It seems to be a very common problem for iPad apps. My guess is that limit comment width only works because there's fewer cells rendered on screen and saved to RAM.

https://www.reddit.com/r/ios/comments/ebano8/ios_133_still_killing_apps_in_the_background/

**Comment by SuperTachyon** [comment]
Thanks for the response. But it’s weird that when width is not limited the app is instantly killed 100% of the time. It shouldn’t be that effective in reducing RAM usage just by limiting the width, even on an iPad Pro.

**Comment by dangwu** [comment]
Did you try turning off Background App Refresh in settings like the reddit
thread mentioned?

**Comment by SuperTachyon** [comment]
I didn’t see any mention for turning background refresh off. It seems that Octal isn’t in the list. I do need to keep background refresh on for a few apps.

BTW, the issue is still the same on iPadOS 13.4 GM.

**Comment by dangwu** [comment]
Oh this thread mentions it a bunch

https://www.reddit.com/r/ios/comments/dar3tq/ios_13_killing_background_apps_way_too/

**Comment by SuperTachyon** [comment]
This is still an outstanding issue that makes the app almost unusable. Here is a video clip that I switch away from Octal to App Store and immediately back. The app should take me to where I left. But instead it goes back to the story list. 


https://streamable.com/q3klh7

**Comment by dangwu** [comment]
I'll see what I can do about saving/restoring state when the app is killed.
This doesn't seem to happen on any other device.

**Comment by SuperTachyon** [comment]
It’s quite to imagine it being specific to this device as the behaviour persisted with multiple OS updates and app re-installations. Maybe it’s model specific or iPad specific. My device is an iPad Pro 10.5. I’ll check if it happens on a regular iPad when I get the chance.

**Comment by SuperTachyon** [comment]
Thanks for the new updates though. The new design looks fantastic!

**Comment by dangwu** [comment]
Sorry I didn't mean your device in particular. It just seems to be a major
iPad Pro issue. Tons of complaints online as I've shown you before. I've
analyzed memory usage with my app and it's consistently low and not leaking
memory, so I'm pretty out of options.

**Comment by SuperTachyon** [comment]
Another observation of the issue: it seems only to occur if and only if it’s in the comments and scrolled down. Hopefully this could hint to something.

**Comment by SuperTachyon** [comment]
I just tried it on an iPad (the most recent gen of the cheapest iPad), the same issue occurs. So it’s most likely to be iPad specific.

**Comment by dangwu** [comment]
Do other apps have this issue? Reddit?

**Comment by SuperTachyon** [comment]
No. Just tried the official reddit client and it works fine. Same goes for “similar” apps like Apollo and Hack.

**Comment by dangwu** [comment]
Do you see their splash screens for a second when resuming the apps?

**Comment by SuperTachyon** [comment]
Mostly no. It seems they usually survive from the system slaughter.

**Comment by dangwu** [comment]
I believe I've fixed this! A very obscure bug for iPadOS where the app will
silently crash in the background if you try to initialize
NSAttributedString from HTML (for comment text). I also fixed a caching bug
that prevented comments from scrolling smoothly... Stay tuned...

**Comment by SuperTachyon** [comment]
Congrats! Looking forward to it.

**Comment by dangwu** [comment]
The fix is with 3.21.0. See if it's fixed! Ccomments should be smoother as well.

**Comment by SuperTachyon** [comment]
Thanks! The crash is fixed finally! Although there’re still some stuttering in scrolling the comments, it’s generally much better now.

**Comment by dangwu** [comment]
Perfect! Good job pushing me until I fixed it! Haha
