### ISSUE TITLE
[Feature] Alternative App Icons

### ISSUE THREAD

**Issue by janniks** [dangwu/Octal#138]
# Alternative App Icons

It is possible in iOS to let the user choose between a set of different app icons. I would love to see this feature in Premium Octal.

Not to be disrespectful, but I find the current Octal 8 icon to be a bit outdated.

I would love to see these options (and more):
- original/current icon
- flat/simplistic/minima version of the octal icon
- dark version of icons above
- something more HN related, i.e. an icon that’s unrelated to the ‘8’ 

I’d be happy to help with icon design 🎨 I like change for change‘s sake—just to keep things fresh and can post some proposals later...

Let me know what you think 💭

**Comment by dangwu** [comment]
I’d be happy to do this if you design it (and I like your designs)!

**Comment by janniks** [comment]
@dangwu that's exciting to hear! Should I post some first ideas/designs here? Or do you want to discuss via Email/DM? 🚀

**Comment by dangwu** [comment]
Email me! Thanks

**Comment by Stanzilla** [comment]
I noticed that you just shipped a black icon today, nice! Could you maybe add one in a dark gray as well?

**Comment by dangwu** [comment]
@Stanzilla yes I can! I'm planning on adding a bunch of icons

**Comment by swrobel** [comment]
@dangwu saw you added alternative icons so I just thought I'd remind you about https://github.com/dangwu/Octal/issues/181

**Comment by dangwu** [comment]
Oh yes, I was actually planning on it!

**Comment by soulseller** [comment]
Unlike Apollo, Octal does not change the icon in the App Switcher.

**Comment by soulseller** [comment]
Unlike Apollo, Octal does not change the App Switcher icon.

**Comment by dangwu** [comment]
@soulseller Reboot your device. It's definitely an iOS system caching bug

**Comment by soulseller** [comment]
Indeed, it still persists probably due to an iOS caching bug. I was not able to reproduce it with Apollo though.

**Comment by soulseller** [comment]
The caching bug still persists even in the latest Octal version (4.2.0). I am not able to reproduce it with different applications that have an alternative icon functionality.

**Comment by soulseller** [comment]
The bug still persists even in the latest Octal version (4.2.0).
I tried to reproduce it (unsuccessfully) with different applications that have an alternative icon functionality.

**Comment by dangwu** [comment]
It's a bug for Apple to solve. See Apollo having the same issue: https://github.com/christianselig/apollo-bugs/issues/594

**Comment by soulseller** [comment]
I completely understand that it is an iOS caching bug that must be fixed by Apple.
Apollo does not have the same issue at the moment. Maybe there's a solution/workaround/hotfix?
