### ISSUE TITLE
Disable full screen swipe to go back

### ISSUE THREAD

**Issue by bryankeller** [dangwu/Octal#139]
The native behavior of swipe to go back should be from the leading edge, not anywhere on the screen. I understand that many apps have gone ahead and overridden this system behavior, but it's a huge pain to accidentally do it when scrolling through comments.

We should at least provide the option to turn off the full-screen edge swipe. My personal opinion is that Apple's UX folks know best here, but I understanding wanting to have an option.

**Comment by dangwu** [comment]
Adding a new setting to toggle this. ETA 24 hours
