### ISSUE TITLE
[invalid] Can't seem to find a way to show favourited posts.

### ISSUE THREAD

**Issue by Snakeyh** [dangwu/Octal#140]
Purchased the premium version in order to favourite some posts so I can read them later, but I am not able to find them anywhere.

**Comment by Snakeyh** [comment]
Nevermind this was a duplicate of #82, solved it by posting a comment. It would be preferable if that wasn't necessary, or at least show a message instead of an blank profile page.

**Comment by dangwu** [comment]
Not a bad idea - I'll add an error message
