### ISSUE TITLE
Layout on Ask HN broken in 3.17.0

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#141]
The OP text is misaligned and wrapped/truncated incorrectly. Will post an example screenshot...

**Comment by luckman212** [comment]
![image](https://user-images.githubusercontent.com/1992842/78213313-52158780-7480-11ea-8504-4a72ecbffa6c.png)

**Comment by dangwu** [comment]
Already submit a build with a fix. Should be out tomorrow! Thanks!

**Comment by luckman212** [comment]
Thanks for everything!
Hope you are safe

**Comment by dangwu** [comment]
No problem! You too! The fix should be available any moment now.

**Comment by luckman212** [comment]
@dangwu Wanted to thank you again for always improving the app. Just dropped a token into the tip jar.

**Comment by dangwu** [comment]
Thank you so much Luke! It means a lot!
