### ISSUE TITLE
[Bug] Poor scrolling performance through a large number of comments 

### ISSUE THREAD

**Issue by Taxyovio** [dangwu/Octal#144]
When scrolling through many comments, especially when using the scrollbar grabber, there are a lot of stutters and lags.

**Comment by dangwu** [comment]
It’s super smooth for me. What device are you using?

**Comment by SuperTachyon** [comment]
I’m using an iPad Pro 10.5. Here is a video clip where I’m just dragging on the scroll bar all the way up and down.

**Comment by SuperTachyon** [comment]
https://streamable.com/6yg67g

**Comment by dangwu** [comment]
Dang, was it always that laggy, or is this a new issue?

**Comment by SuperTachyon** [comment]
This has been the case for as long as I can remember. Definitely not something new in the last few months.

**Comment by dangwu** [comment]
Do you experience issues in other apps as well?

**Comment by SuperTachyon** [comment]
No. It’s unique in Octal.

**Comment by SuperTachyon** [comment]
- It’s been mostly eliminated as in the last update. Thanks!

**Comment by Taxyovio** [comment]
This issue seems to be haunting again. It’s a bit nitpicking but for thousands of comments, the scrolling is basically skipping. [](https://streamable.com/n17e2v)

**Comment by dangwu** [comment]
This should be vastly improved since 4.0.0. Let me know if it hasn't!

**Comment by Taxyovio** [comment]
It’s improved a lot. Thanks! Now the stuttering can only be seen when scrolling through more than about 200 comments.
