### ISSUE TITLE
[Feature] Putting “Jobs” together with sort order doesn’t seem to make any sense

### ISSUE THREAD

**Issue by SuperTachyon** [dangwu/Octal#145]
In the recent update, search has been moved to a dedicated tab replacing the jobs tab, which is now hidden in the sort order menu. 

I don’t understand the logic behind in this change. It feels very out of place to out jobs there.

**Comment by dangwu** [comment]
Don’t worry, I have a big update coming that changes filters drastically! I
just needed a temporary place to put Jobs since it didn’t need it’s own tab.
