### ISSUE TITLE
[Bug] Delay when switching between dark and light mode

### ISSUE THREAD

**Issue by SuperTachyon** [dangwu/Octal#146]
Not sure if this counts as a bug. There is a short delay when switching between dark and light modes, which doesn’t exist in native and other third party apps.

**Comment by dangwu** [comment]
Yeah I'm aware of this. It's due to my custom theming implementation which
allows for more than just Light/Dark. I'd likely have to remove True Dark
to go full native Dark Mode.

**Comment by SuperTachyon** [comment]
I think it’s still possible to have different themed dark modes. For example, there’s a popular (free) reddit app, Apollo, which has three levels of darkness for dark mode. I’m not sure if it’s native or custom, though its dark mode transition is instantaneous.

![image](https://user-images.githubusercontent.com/38234151/79784994-0b0e0a00-833b-11ea-8985-9c0d6ade7f0e.png)

**Comment by dangwu** [comment]
Ohhh you're talking about actually delay when toggling the switch? Gotcha.
Yeah it's possible for me to improve upon that but I don't see that as a
bug...

**Comment by SuperTachyon** [comment]
Sure. It’s just me nitpicking here. lol

**Comment by SuperTachyon** [comment]
In the lastest update, this is not just a delay any more. It straight up stopped switching mode based on system settings. https://streamable.com/2bknry

**Comment by dangwu** [comment]
I noticed this too. Have a fix but app got rejected. Working through an
appeal.
