### ISSUE TITLE
[Feature] Customize navigation tabs

### ISSUE THREAD

**Issue by swrobel** [dangwu/Octal#147]
I love that MiniHack lets me customize the navigation tabs - specifically that I can put Best / Front Page (aka Top) down there instead of needing to use the filter icon in the top left to switch between them.
![2020-04-20 15 12 35](https://user-images.githubusercontent.com/157270/79804733-79da6b80-8319-11ea-8eaf-6644a57cd4e5.png)

**Comment by dangwu** [comment]
Good timing! I have a new update coming out that refresh the UI and
(hopefully) makes all these filters much easier to use! Stay tuned! ETA 2-3
days.

**Comment by dangwu** [comment]
Update is out

**Comment by swrobel** [comment]
Thanks, Dan! This is an improvement, but ... I hate to be really persnickety, but I'd love to be able to customize the order of these or just de-select certain options. My common use-case, as mentioned, is toggling between Top & Best, but I don't spend very much time on Ask/Show, and those are between my two favorite options, which means I have to swipe to scroll them on my iPhone X to get between Top/Best.

**Comment by dangwu** [comment]
I see your point... Not promising anything, but what if I just moved *Best*
to the direct right of *Top*?

**Comment by swrobel** [comment]
💯

**Comment by swrobel** [comment]
Oh I might suggest removing "stories" from each of the buttons... Then more of them would fit in screen without scrolling

**Comment by dangwu** [comment]
I have an update coming soon that lets you rearrange the filters and swipe
between them!

**Comment by swrobel** [comment]
latest update is perfect... Thank you!!! 🎉
