### ISSUE TITLE
[Feature] Being able to swipe to navigate

### ISSUE THREAD

**Issue by BigManatee** [dangwu/Octal#148]
I just got the new design and it's looking great but I already miss the navigation buttons at the bottom for Top/Ask/Show etc.
It'll be great (to me) if you were able to swipe left or right anywhere to change the category when you're on the feed!

*v3.19.0 btw*

**Comment by dangwu** [comment]
Thanks! I'm 100% planning on adding ability to swipe left/right between the
filters. I want that badly myself :) Stay tuned.

**Comment by BigManatee** [comment]
That's great to hear, I look forward to it! 
Thanks for all your work on the app

**Comment by dangwu** [comment]
3.20.0 is out today which has swiping between filters. Enjoy!
