### ISSUE TITLE
The redesign is great, but please get rid of the weird material design color thing in the tab bar.

### ISSUE THREAD

**Issue by jameslittle230** [dangwu/Octal#149]
It's not subtle enough and the animation is jarringly fast and it makes me sad to use it :/

I don't want to be a downer, though -- the rest of the app is _awesome_.

**Comment by janniks** [comment]
I agree ☝🏻 It seems very distracting and krass, while being very atypical for iOS...

**Comment by dangwu** [comment]
I actually just changed the animation color to always be the blue filter color. Google News has a similar animation. Sorry for the annoyance but I’m not getting rid of it.
