### ISSUE TITLE
3.20 - per-section filtering - please being back

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#150]
I saw this comment https://github.com/dangwu/Octal/issues/145#issuecomment-616173743 so please forgive me if the redesign is still a work in progress. I'm still getting used to it. Mostly I really love it, but there are a couple of drawbacks, such as having to scroll up to see which section you're in. I realize this is a trade-off for slightly more screen space for stories.

Anyway, this issue is about the filters being "global" now and affecting all tabs equally - Top, Show, Ask etc. This doesn't really work well, since Top stories get on average 10-100x the number of votes as other sections. I had good settings before for each, but now most tabs show only a couple of stories.

Hope the per-section filtering can be restored! thank you

**Comment by dangwu** [comment]
Ah, I can see how this ruined your usage! Sorry about that. I’ll ponder over UX to make them per category instead of global.

**Comment by luckman212** [comment]
I appreciate that, thank you!

**Comment by luckman212** [comment]
I didn't want to open up a whole new issue for this, so I'll put these 3 comments here:

I think the top nav can be optimized a bit more (save space) by shortening the titles to just "Top, Show, Ask, Best, New, Jobs". This would allow jumping to sections to mostly fit on a single screenpage width without needing to use 2 gestures (swipe then tap).

If possible could you also bring back the caching so the views don't refetch with each L/R swipe (unless we pull down to refresh).

Also, the view when all the way "left" (typically Top Stories) still allows you to swipe left, even though you end up back on the same view, so it just causes a somewhat confusing refresh and animation. Same thing for swiping right from the rightmost view. Not sure if those can be avoided.

**Comment by dangwu** [comment]
Good stuff! I was planning on doing the caching! You're not a professional
QA are you? :P

**Comment by luckman212** [comment]
> You're not a professional QA are you?

Unfortunately no, I just have OCD... 😊

**Comment by luckman212** [comment]
@dangwu Not trying to rush you, but hoping this is still planned! HN is tough for me to wade through without proper filters.

**Comment by dangwu** [comment]
Didn't forget! Will work on this soon!

**Comment by dangwu** [comment]
Released today! Let me know if you find further issues

**Comment by luckman212** [comment]
Amazing!
Tip Jar Activated! 🙂

**Comment by dangwu** [comment]
Please save your money and treat yourself for helping me so much 😬
