### ISSUE TITLE
[Bug] Screen refreshing several times after upvoting

### ISSUE THREAD

**Issue by swrobel** [dangwu/Octal#151]
The second refresh wasn’t triggered by any user action (not that I think the first should’ve happened). This happens pretty often on my iPad mini 5. I’m on the latest App Store release. 

![image](https://user-images.githubusercontent.com/157270/80675849-5d9da380-8a6a-11ea-962d-9fddb3be137c.gif)

**Comment by swrobel** [comment]
Seeing this on my iPhone X as well. It's triggered by an upvote or removing one (tapping an existing on again as shown in the screencast above)

**Comment by dangwu** [comment]
Thanks guys. Will definitely work on fixing this one. It's the same
weirdness when collapsing/expanding a comment near the top of the screen.

**Comment by dangwu** [comment]
Fix is in App Store review

**Comment by dangwu** [comment]
Should be fixed!
