### ISSUE TITLE
[Bug] Slight UI imperfections when loading stories/comments

### ISSUE THREAD

**Issue by Taxyovio** [dangwu/Octal#153]
When stories and comments are being loaded, there’re those grey placeholder strips for the texts. The length of those strips starts a bit too short before extending to the appropriate length. See the video clip taken on iPad Pro 12.9.

[Video clip](https://streamable.com/2b40eu)

**Comment by dangwu** [comment]
Yup I’ve noticed this too. Will fix

**Comment by SuperTachyon** [comment]
I just noticed that this seems to only happen on cold launch but not on pull to refresh.

**Comment by dangwu** [comment]
Fix coming
