### ISSUE TITLE
[bug] can't scroll up after collapsing comments

### ISSUE THREAD

**Issue by swrobel** [dangwu/Octal#154]
In this case I collapsed a bunch of replies to a comment then couldn't scroll above that point  https://youtu.be/q6jvm8hbkZM

**Comment by dangwu** [comment]
The video won’t play for me

**Comment by dangwu** [comment]
Ah I’ve reproduced it! Will fix. Thanks for letting me know

**Comment by dangwu** [comment]
Fixed in today’s release
