### ISSUE TITLE
Add a “Mark As Read/Unread” Function

### ISSUE THREAD

**Issue by iamrecursion** [dangwu/Octal#155]
Sometimes I’ll tap through onto a story that I want to come back to later, so it would be great to be able to swipe on stories to mark them as unread or read.

**Comment by dangwu** [comment]
Good idea! And simple enough to add. Will probably add soon in the long
press menu :)

**Comment by iamrecursion** [comment]
Brilliant!

**Comment by dangwu** [comment]
Unread is in!

**Comment by dangwu** [comment]
Didn't add 'read' b/c I don't see it as a common use case, it's simple enough to just enter/leave a story if you *really* wanted to.

**Comment by iamrecursion** [comment]
Great! I love it!
