### ISSUE TITLE
[BUG] links don’t load in safari in-app even if selected in settings

### ISSUE THREAD

**Issue by herjazz** [dangwu/Octal#157]
As per title. Instead they load in Safari proper. Have changed setting to safari and then back to safari in-app, however the problem persists. 

Iphone 6, iOS 12.4.6

Paid and most recent version of app.

**Comment by dangwu** [comment]
Not happening for me. Are you on the latest version of Octal?

**Comment by herjazz** [comment]
Ahh I won’t be because I’m using ios 12. Your most recent version is ios 13 and up.   
  

  
  
  

  
  
>

**Comment by dangwu** [comment]
Ah yeah you gotta update! What’s stopping you?

**Comment by herjazz** [comment]
I’m on an iphone 6 so I cannot use ios 13. It’s no longer supported unfortunately.   
  

  
  
  

  
  
>

**Comment by dangwu** [comment]
What version of the app are you using? I can likely fix this for you

**Comment by herjazz** [comment]
Hi,
  

  
Sorry about slow reply. I can’t actually find the version number in the app. I’m guessing it’s the last one that could be used in ios 12. I noticed that whatever browser I put in the settings to use it still will open the page in safari.   
  

  
Thanks,
  

  
William   
  

  
  
  

  
  
>

**Comment by matthew-p-gilley** [comment]
I’m experiencing the same issue, of not loading links with In-App Safari, on an iPad Air 1st gen running iOS 12.4.7 with the last version of Octal available for iOS 12.4.7

**Comment by dangwu** [comment]
Can you go to Octal in the App Store and see what version of the app you
have installed?

**Comment by matthew-p-gilley** [comment]
@dangwu Version 3.11.2

**Comment by dangwu** [comment]
Thank you! Try killing the app and seeing if the issue is resolved!

**Comment by matthew-p-gilley** [comment]
@dangwu That seems to have resolved the issue here, thank you!

**Comment by dangwu** [comment]
Awesome!

**Comment by herjazz** [comment]
Same for me too. Thanks!
  

  
  

  
  
>
