### ISSUE TITLE
Collapse Comment Thread to Root

### ISSUE THREAD

**Issue by iamrecursion** [dangwu/Octal#158]
Sometimes you get deep into a comment thread and decide you're done with it, and want to see the next top-level comment. It would be great to have a gesture (or menu option) on child comments that can collapse an entire thread back to the top-level. 

This could be _further_ enhanced by having the viewer automatically scroll so that the top of the next comment is in view when collapsing one, rather than it sometimes getting dragged off screen like it currently does!

**Comment by dangwu** [comment]
There’s already a button to jump to the next to level comment

**Comment by iamrecursion** [comment]
Can you clarify which button this is? I haven't found any UI element that lets me do what I've described!

**Comment by dangwu** [comment]
Here it is. You can drag it around too

**Comment by iamrecursion** [comment]
I don't see anything attached? :o

**Comment by dangwu** [comment]
Ah sorry. Here it is:

![image](https://user-images.githubusercontent.com/5155951/82080925-4da4d700-969a-11ea-96db-60512c9145a3.jpeg)

**Comment by iamrecursion** [comment]
Ah! That does _part_ of what I was hoping for. The other part is the problem that there’s no easy way to collapse a comment chain to its root, and when you do collapse a long thread it may scroll the subsequent top level comment off the top of the screen.

**Comment by iamrecursion** [comment]
In essence, I’m used to this behaviour from the unmaintained MiniHack.

**Comment by dangwu** [comment]
I see. But if the end goal is to read the next top-level comment, isn’t the
down arrow button enough? I’ll see about adding a new option in the
overflow menu to collapse a root comment either way.

**Comment by dangwu** [comment]
Adding in next release (this week)

**Comment by iamrecursion** [comment]
Awesome!

And if the end goal is that, it does work! It's just a different mode of operation I guess!

**Comment by dangwu** [comment]
Added

**Comment by iamrecursion** [comment]
Brilliant! Thank you so much! I've already got premium, but these two features make such a difference to my experience that I've thrown you a big tip as well! I love Octal for reading HN. ^^
