### ISSUE TITLE
[Bug] crash when searching

### ISSUE THREAD

**Issue by swrobel** [dangwu/Octal#159]
Search "Zerotrus" and it crashes every time. Weirdly only when typing it out. Pasting is fine.

**Comment by luckman212** [comment]
Same for me. Weird bug!

**Comment by dangwu** [comment]
I’ll take a look. Thanks!

**Comment by Purstal** [comment]
Searching "Youtube blackmail" also makes the app crash, even by copying and pasting It

I'm using an iPad and although I can't find the app version inside the app, since it is up to date, it should be 3.28.0.
I think it would be a good idea to put the app version inside the app.

**Comment by dangwu** [comment]
Fixed!
