### ISSUE TITLE
After posting comment, it doesn't appear

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#16]
I noticed that after submitting a comment using Octal, it did not appear in my view. I had to scroll to the top and then pull down to refresh. 

It should refresh automatically after the comment is submitted.

**Comment by dangwu** [comment]
I actually do refresh comments after around 5 seconds, but it seems to often not be enough time. The API has a bit of a non-constant delay for displaying new comments. I'll revisit this and make it smarter.

**Comment by dangwu** [comment]
This should work slightly better now. I added multiple retries.

**Comment by dangwu** [comment]
This should work *way* better now in 3.2.2!

**Comment by luckman212** [comment]
I just tested posting a comment in 3.2.2

How long is it supposed to take to appear? I would estimate it took about 20 seconds. I noticed there was no "flickering" or reloading like there was before, but it still seems like a long time. I guess this is just an API limitation.

**Comment by dangwu** [comment]
Yeah that sounds about right. It's a limitation of the API, unfortunately.
I'm essentially using a web socket to listen for the exact moment the new
comment comes through the stream, instead of polling for it.
