### ISSUE TITLE
Unnecessary ellipses on "Hacker News" heading

### ISSUE THREAD

**Issue by benjrichardson** [dangwu/Octal#160]
As in the title. Seems like there's plenty of horizontal space to fit, but the last two characters are getting replaced with an ellipses. It's happening no matter what my text size is set to.

<img width="320" alt="screenshot" src="https://user-images.githubusercontent.com/21092217/83294849-051e0b00-a1bc-11ea-87e2-1da3da3d9c77.png">

Hardware: iPhone SE (the 1st-gen one with the teeny screen)
Software: iOS 13.4.1

**Comment by dangwu** [comment]
Whoa! I need to test on the SE more. Thanks for the report!

**Comment by dangwu** [comment]
Fixed!
