### ISSUE TITLE
[Bug] Text cannot be copied from Ask HN (the sequel)

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#161]
Somewhere along the way, this issue that you fixed last year came back! (Text cannot be copied from Ask HN — #57)

Using 3.28.1 btw

**Comment by dangwu** [comment]
Good find! Must have broke when I updated the header. Will fix

**Comment by luckman212** [comment]
@dangwu Do you think this is also related to why hyperlinks don't work in the header posts too?

E.g.

Show HN: Midnight.pub – Virtual Speakeasy https://news.ycombinator.com/item?id=23868295

**Comment by dangwu** [comment]
Probably, yeah. I rewrote the header code recently and it all broke at that
time 😅. Will fix it all shortly!

**Comment by dangwu** [comment]
Fixing coming
