### ISSUE TITLE
[Bug] Attempting to create a post with a title that is too long provides an unclear error message

### ISSUE THREAD

**Issue by jonpalmisc** [dangwu/Octal#162]
I’m not familiar with the HN API (maybe this is an API limitation), but I tried creating a post with too long of a title and got a generic error message (see picture). Ideally, you would be told your title is too long.

![image](https://user-images.githubusercontent.com/41548458/85638344-a7ae9a00-b653-11ea-930f-bc99214233f1.jpeg)

**Comment by dangwu** [comment]
Good find!

**Comment by dangwu** [comment]
Added error message now! Awaiting Apple review
