### ISSUE TITLE
[Bug] Upvote button(s) are very small

### ISSUE THREAD

**Issue by aryounce** [dangwu/Octal#163]
The tap target is extremely small for the upvote buttons. Could it be made larger?

**Note**: The only other gesture I could find for upvoting is long pressing an article listing. Down-voting (which I believe I have enough HN “karma” to do, doesn’t appear to be supported.

**Comment by aryounce** [comment]
Gestures for up/down voting would also be greatly appreciated.

**Comment by dangwu** [comment]
Thanks for the feedback. Will consider updating the design/size in next UI revision
