### ISSUE TITLE
[Bug] Links from origin (top) posts are not clickable

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#164]
Might be related to #161

Good example with a lot of links, they show up underlined/blue but are not clickable:

Launch HN: Mindset Health (YC S19) – Hypnotherapy apps for chronic conditions https://news.ycombinator.com/item?id=23875636

**Comment by axsuul** [comment]
Also seeing this issue as well!

**Comment by dangwu** [comment]
Fix coming

**Comment by dangwu** [comment]
Update: Apple is rejecting the new app update from the App Store, so I'm in a lengthy appeal process.

**Comment by luckman212** [comment]
Why are they rejecting? I would think they would leave you alone and focus on their billion-dollar fight with Epic/Fortnite. Seems no rock is too small for Apple to turn over these days. ☹️

**Comment by dangwu** [comment]
First it was for Guideline 5.1.1 - Data Collection and Storage, related to displaying COVID-19-related submissions. Now it's for Guideline 4.2.2 - Design - Minimum Functionality. Appeal in progress...
