### ISSUE TITLE
[Feature] Collapse to root comment

### ISSUE THREAD

**Issue by inickt** [dangwu/Octal#165]
Not sure if you have used Apollo before but I love its comment navigation/interaction system. Combined with #97 it would be great to be able to collapse a whole chain of comments, instead of scrolling back up to the root comment. Jump to next chain is great but I would love being able to collapse!

Thank you for making such a great app!

**Comment by dangwu** [comment]
Collapse to root comment is already an option in the comment overflow menu 😃

**Comment by inickt** [comment]
Ah nice! Never noticed that there! Would love a way of exposing that in a single gesture/tap instead of 2 but that works for now. If you end up adding the swipe gestures I would love that to be one of the options 😄 . Thanks again!

**Comment by timbeccue** [comment]
Just wanted to add that I use left swipe to collapse the root comment very frequently in Apollo and other apps. In fact, I sometimes use the "Hackers" app instead of Octal solely for that ability. If Octal included that functionality, I would be a very happy camper 😀
