### ISSUE TITLE
How do I turn off “swipe to change categories”?

### ISSUE THREAD

**Issue by bknowles** [dangwu/Octal#166]
I don’t mind the feature existing, but it’s extremely frustrating to try to clean my screen and have Octal think that means I want to switch from one category to another, and completely lose the place where I was reading articles.

I want to be able to individually turn off all swipe functions of any sort.  Scrolling is good, but not swiping.

**Comment by dangwu** [comment]
Probably not going to happen. Almost every app has non-disableable swipe
gestures... clean your screen carefully 😅
