### ISSUE TITLE
Option to reduce unnecessary network activity

### ISSUE THREAD

**Issue by lightswitch05** [dangwu/Octal#169]
Hello, when I use this app- I see every website showing up in my PiHole logs. I believe this might be to load up the site's favicon? I don't particularly want every hackernews site to receive web requests from my device. An option to disable this extra network activity would be really appreciated.

Thanks!

**Comment by dangwu** [comment]
There’s an existing option to hide fav icons and images. It should work for
you.

**Comment by lightswitch05** [comment]
I didn't realize they didn't load on minimal layout. Thanks!
