### ISSUE TITLE
Feature request: filter stories < # points

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#17]
I am addicted to HN but sometimes there isn't enough time to scan thru all the stories. For those times I sometimes use https://hckrnews.com which is great.

But on mobile, using Octal is a much better experience! I wish there was a filter we could toggle on/off to hide stories below a certain threshold e.g. "only show stories with 50 points or more"

**Comment by luckman212** [comment]
It's similar, but the algorithm that generates "Best Stories" seems to have a broader set of criteria. It shows stories that are up to 4 days old.  I am really trying to filter for the hottest stories of the current day.

Also, this filter would really help in the "Show HN" section. Many posts there receive 0 replies. But, a few of them generate lots of replies, and these are the ones I really like to read. So, I often scroll through the view looking for the posts that have activity. Being able to filter it so it only shows posts with >5 comments (e.g.) would really help.

**Comment by dangwu** [comment]
Added with v2.9.0!

**Comment by luckman212** [comment]
@dangwu Thank you so much for adding this feature! I feel bad even asking but would you consider adding the filter to the other views (Ask, Show) also?

**Comment by dangwu** [comment]
That's easy enough. Will add this week :)
