### ISSUE TITLE
[Bug] Search sometimes doesn’t show results until pulling to refresh 

### ISSUE THREAD

**Issue by Taxyovio** [dangwu/Octal#170]
Tested on iPad on both iOS 13 and 14 beta.

**Comment by SuperTachyon** [comment]
There’s also a likely related issue where the top results are not shown on the search page.

**Comment by dangwu** [comment]
Yeah I've noticed this happened extremely rarely. Will keep an eye out. My guess is that it's a bug with the search API.

**Comment by SuperTachyon** [comment]
I don’t think it’s very rare as I just reproduced it again. I’m seeing this happening almost every other time I do a search. 

Also maybe related: the search page doesn’t show the trending stories until refreshing manually.

**Comment by dangwu** [comment]
Interesting. I haven’t seen the issue in weeks. Are you possibly using an
IP address that’s hitting the API rate limits (10k/hour)?

**Comment by SuperTachyon** [comment]
I don’t think so. I’m pretty sure I’m the only one browsing hn in my house...
