### ISSUE TITLE
[Bug] Odd screen redraw flicker I noticed today

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#171]
Happens when loading the comments for this Top story:

Level 3 Global Outage
https://news.ycombinator.com/item?id=24322861

screen recording:
https://streamable.com/9so7ce

- iOS 13.6.1
- iPhone Xs

**Comment by dangwu** [comment]
I saw this too! I have a strong suspicion that the Firebase API was sending
a bunch of crazy data that thread.

**Comment by dangwu** [comment]
Also, I *do* plan on fixing the other bugs you found regarding the
inability to highlight header text. Been super busy!

**Comment by dangwu** [comment]
Stopped seeing this. Resolving as likely API defect.
