### ISSUE TITLE
UI issues 

### ISSUE THREAD

**Issue by twodayslate** [dangwu/Octal#173]
![DFB44C73-25DD-4B43-841B-37B827DFA016](https://user-images.githubusercontent.com/1085707/92678465-0c44d100-f2f4-11ea-9f21-4685679634f7.png)

Go down arrow in wrong place and add comment bar covers contents.

**Comment by dangwu** [comment]
1. Hold and drag the down arrow to wherever you want it
2. The add comment footer auto-dismisses when scrolling down
