### ISSUE TITLE
[Feature] Rainbow comment lines

### ISSUE THREAD

**Issue by monkinco** [dangwu/Octal#174]
Adding color to comment lines would greatly improve readability and staying on topic. Now with a lot of comments you can easily get lost in all of them. :)

Apollo app as an example: 
![8994730F-E479-47CC-834A-447A9518951A](https://user-images.githubusercontent.com/41922527/93646406-72250d00-fa06-11ea-8e14-4e9a19e7d7da.jpeg)

**Comment by dangwu** [comment]
Will consider. Since my thread lines are continuous it's not as hard to track as Apollo

**Comment by monkinco** [comment]
> Will consider. Since my thread lines are continuous it's not as hard to track as Apollo

It will still adds additional points to readability as with hundreds of comments it’s starting to get hard to grasp. :)
