### ISSUE TITLE
App Store Review

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#175]
What can we (your happy users) do to help get Apple off your back with these baseless "violations" ?

I miss the updates and it's terrible they are making you go through this waste of time instead of putting that energy into Octal.

Is there some way we can petition them or someone to email? Some case to reference?

**Comment by dangwu** [comment]
I recently started working on an update that "addresses" some of their "violations" ;) Hopefully it goes through. I highly doubt that petitioning or emailing will accomplish anything, but I appreciate your support!
