### ISSUE TITLE
Bug in "Activity" view from user profile (3.29)

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#178]
Tapping on your user profile > Activity > any comment, leads to a weird page with the comment at the top and then repeated again just below. There is no way to view the comment in context of the thread, as you could before.

Tapping the three dots (...) and then clicking "View Thread" just loops you back to the same screen and nests you deeper into an endless breadcrumb loop...

**Comment by dangwu** [comment]
Dang, good find! Will fix.
