### ISSUE TITLE
UI bug in Favorites view - 3.29

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#179]
Tap on User Profile > Favorites

The toggler at the top has a weird clipping mask glitch. Look at the corners closely and you'll see it...

It's also especially visible when flipping between Stories and Comments...

![2BABCDA9-ED48-4D02-A8B1-A75749158C93](https://user-images.githubusercontent.com/1992842/96073058-9e9c3f80-0e73-11eb-903f-0729b1391712.jpeg)

**Comment by dangwu** [comment]
Noticed this too. Will fix!
