### ISSUE TITLE
New UI doesn’t go directly to link

### ISSUE THREAD

**Issue by darsnack** [dangwu/Octal#180]
The new UI is scrunched to the left side, making it hard to reach for new users. Getting directly to the linked article also requires two screens, and the second screen has the link placed at the top which is again hard to reach.

![Screenshot example](https://user-images.githubusercontent.com/4811350/96325553-bbad4b80-0ff6-11eb-9cea-f28797ecd4c0.jpeg)

**Comment by mikeknoop** [comment]
I tend to like this new comment behavior myself. Perhaps could be a setting for those who don’t?

The other new layout issue I noticed was favicons are removed in “compact” mode shown in the screenshot above. I miss those — they give a bit of distinguishment to each story while maintaining story density. Could this be considered as anothet feature/setting to bring back?

**Comment by dangwu** [comment]
Note to OP - you can tap the host name from the first screen to go straight to the web link. In full mode you can also tap the cover photo. I can definitely add more customization around what opens by default and favicon display.

**Comment by darsnack** [comment]
Thanks! That definitely helps the situation, and making the favicon clickable will help too.

**Comment by simonsmithies** [comment]
Although in compact mode you can click the host name to go direct to the link, I find that is too small a target to reliably hit on a phone screen, and I still end up on the comments page about half the time.

**Comment by dangwu** [comment]
New version today adds a "Story Destination" setting to let you pick whether tapping a story goes to comments or the URL.
