### ISSUE TITLE
Navigation back stack view displays as empty

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#182]
Noticed this first on 3.28 but it still exists in 3.33.

Long pressing on the back ←arrow in the header opens a blank popup balloon. Picture (video) worth 1000 words...

![RPReplay_Final1603023671b](https://user-images.githubusercontent.com/1992842/97054987-da11ca80-1553-11eb-9c1e-4c3e81415780.png)

**Comment by dangwu** [comment]
Whoa. Will take a look

**Comment by luckman212** [comment]
3.33 still has this (you probably know)

**Comment by dangwu** [comment]
Yeah I'm aware. It's iOS14's new back stack menu behavior. Stop long
pressing back for now ;)

**Comment by dangwu** [comment]
Fixed
