### ISSUE TITLE
Text gets lost upon editing a post

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#183]
Just noticed this (3.31.0) 

Not sure if it's related to the 4-space indented text or just any post that has multiple paragraphs of text, but I posted something using Octal that had 4-space indented (monospace) text. I needed to make a small correction so I went back to edit it, and found that upon tapping Edit, the displayed post was missing everything from the end of the first text block onward.  🙀 

from
![image](https://user-images.githubusercontent.com/1992842/97184505-5e8f6380-1775-11eb-923b-96b13ea686e2.png)

to
![image](https://user-images.githubusercontent.com/1992842/97184966-e2495000-1775-11eb-9f4e-aeeb0439bdaf.png)

Here's a screen recording:
![RPReplay_Final1603675409](https://user-images.githubusercontent.com/1992842/97184300-25ef8a00-1775-11eb-99a1-b4ceb96c7b45.png)

**Comment by dangwu** [comment]
Weird. Will take a look

**Comment by dangwu** [comment]
New version today fixes this bug!
