### ISSUE TITLE
Crashes Immediately on Open

### ISSUE THREAD

**Issue by unstatusthequo** [dangwu/Octal#185]
Since last update, the app is crashing immediately on open. Happening both on iPhone and iPad devices

**Comment by dangwu** [comment]
Strange. I’ll scour crash reports. Meanwhile does a fresh uninstall then
install fix the issue?

**Comment by unstatusthequo** [comment]
It does, so seems like just minor issue with upgrade from prior version.

Regards,

Richard

**Comment by neuhaus** [comment]
I have the same issue.
It crashes on startup (after showing the stories). 
I updated to the latest version but it still crashes.

**Comment by dangwu** [comment]
Thanks for the reports. I've located the likely cause and am submitting a fix right now!

**Comment by neuhaus** [comment]
The update 3.33.2 fixed the issue for me! Thank you.

**Comment by dangwu** [comment]
Perfect!
