### ISSUE TITLE
Accessibility: when clicking on an article link  using voiceover wrong webpage is opened 

### ISSUE THREAD

**Issue by markcartertm** [dangwu/Octal#186]
On iOS go to iOS settings accessibility and turn on voiceover. Now go back to the app and try to Open in the article in the list. Note that it will open the route of the website the article links to rather than the exact URL for the article. This makes the app completely unusable for visually impaired users.

**Comment by dangwu** [comment]
Thanks for the reports. I'll need to make an update with all these accessibility fixes.

**Comment by dangwu** [comment]
Hi @markcartertm, can you further explain the issue? I Just tried it myself and it opens the full URL as expected.
