### ISSUE TITLE
“Next comment thread” button can be moved offscreen and never recovered

### ISSUE THREAD

**Issue by BenKesselring** [dangwu/Octal#188]
I was trying to put the “next comment thread” button as close to the lower-left corner of my screen as possible, and it got stuck off the left side of the screen - it’s rendered there when swiping back (see image), but cannot be interacted with, and disappears then the swipe-back action is completed. This behavior persists through closing and reopening the app.

![button off-screen when swiping back](https://user-images.githubusercontent.com/3117644/101384717-08373980-3878-11eb-9f23-53987cd60d04.png)

**Comment by dangwu** [comment]
Sorry, you'll have to uninstall and reinstall the app! I don't have any way to reset this preference
