### ISSUE TITLE
Font colour of comments don’t change when Auto Night Mode activates

### ISSUE THREAD

**Issue by disposedtrolley** [dangwu/Octal#19]
I’ve just experienced this today on my iPhone X running 12.1.2 - it’s quite hard to replicate from my end with a screenshot unless I wait for the night mode to deactivate in the morning, so apologies for lack of visual feedback!

Steps to hopefully replicate:
1. Ensure Auto Night Mode is enabled but not active
1. Open the comments page for a post
2. Switch to a different app and wait until the time night mode should trigger itself
3. Switch back to Octal, which should transition to night mode
4. The font colour of the comment text should still be black

**Comment by dangwu** [comment]
Fixed with v2.7.0 released today
