### ISSUE TITLE
I cannot create my account

### ISSUE THREAD

**Issue by reizya** [dangwu/Octal#193]
when I try to create my account, it went "something went wrong please try again later"
but I already paid 30 for the premium version, what can I do next?
pls help

**Comment by dangwu** [comment]
Hello, can you force restart the app and try again? I've remotely enabled
sign in via webview. You were probably hitting a captcha.

**Comment by dangwu** [comment]
You can also create the account at news.ycombinator.com, then login to Octal with that account.
