### ISSUE TITLE
[Feature Request] Enable Support for M1 Macs

### ISSUE THREAD

**Issue by Jcowwell** [dangwu/Octal#195]
Side-loaded a bunch of apps to my M1 Mac and Octal works perfectly. Any plans to enable download from the M1 Mac App Store for updates?

**Comment by dangwu** [comment]
Interesting... how did you side load? I have no plans right now, but I want to try it myself. I'm wary of just adding another platform if it's going to slow down development speed of iOS.

**Comment by Jcowwell** [comment]
Via the iMazing. Allows you to export IPA files off of an iOS or iPadOS device. Octal has been phenomenal and honestly doesn’t seem to need any changes. My only worry is that eventually as more updates are pushed out the version I’m using will break and Octal will become unavailable since Apple will disable this kind of sideloading in future updates.

**Comment by dangwu** [comment]
Ok I'm going to enable M1 support to get the fancy "Designed for iPad" badge... :) Please let me know if you encounter any bugs or anything. I don't have an M1 yet!

**Comment by dangwu** [comment]
@Jcowwell I'm curious - does changing the app icon work on Mac?

**Comment by Jcowwell** [comment]
Just tested it, it does not.

**Comment by dangwu** [comment]
Damn, thanks for checking!
