### ISSUE TITLE
Blue

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#197]
Hi @dangwu 👋 
Thanks for pushing v4.0! I am not a big fan of the new blue color on the top & bottom nav buttons though. It looks ok in the light theme, but in Dark, it's much lower contrast than the old shade. Just doesn't feel right. Maybe I was too used to the old color after years of use. But, I would like to see it brought back...

**Comment by dangwu** [comment]
I'm planning to take a big pass on all the colors to try to get them more aligned with Apple's standard ones!

**Comment by luckman212** [comment]
Thanks. Sorry for this nitpick. That's what happens when you have a nearly perfect app ... people start complaining about the colors 😃

**Comment by dangwu** [comment]
Hah!

**Comment by luckman212** [comment]
Looking better in 4.1.0  👍

**Comment by luckman212** [comment]
Continued nitpicking... discussion from #202

Apple's
![image](https://user-images.githubusercontent.com/1992842/114292802-3c597b80-9a5f-11eb-8b39-d8783516f1e1.jpeg)

vs. Octal's
![image](https://user-images.githubusercontent.com/1992842/114292809-411e2f80-9a5f-11eb-8e10-4b01cd2cda05.jpeg)

**Comment by dangwu** [comment]
Thanks! That does look better!

**Comment by dangwu** [comment]
That blue from the Mail app is now being used in 4.4!

**Comment by luckman212** [comment]
oh man that is beautiful 💙
