### ISSUE TITLE
[Feature Request] Please re-enable single-pane mode

### ISSUE THREAD

**Issue by benhj** [dangwu/Octal#198]
Hi Daniel,

With version 4.0.0, it seems that Octal has resorted to a two-pane viewing mode. I'm an iPad user and I much preffered the original single-pane mode. Thus if possible, please could you at least add a settings option that allows us to restore this original view. I paid for this app and one of the things I always loved about it was it's clear parity with the desktop website.

Thanks and best wishes,
Ben.

**Comment by voiprodrigo** [comment]
Completely agree. This two pane layout does not work at all for me using the iPad horizontally. Please add option to revert. This should not be forced on users. 
Thank you!

**Comment by dangwu** [comment]
Hey guys - please explain how the native, Apple-recommended two column
layout ruins the experience. I would love to understand.

**Comment by voiprodrigo** [comment]
Previously I could read the titles normally, in one line. And it was easy to browse the titles that way. Now i have titles in a narrow column split in 4 or 5 lines, and only 3 or 4 fit in the screen at a time. Also previously page content would fit the whole window, it was clean, now it's a narrower window as well, so even more scrolling, with distracting surrounding, like a html popup. 

I think the new layout is fine for the comments section, but I don't like it for everything else. I don't see what is the point of being apples official way. It surely fits apps where there is navigation on the left, but the titles in this case are not navigation, IMHO. To be honest, this really feels like a different app for me.

**Comment by dozernz** [comment]
I would also like the ability to go back to single pane view. I use Octal on an iPhone 8 and also splits the panes horizontally. This makes one handed navigation very difficult. Also having the stories pane visible is not really helpful when I'm trying to read comments.

**Comment by dangwu** [comment]
Ok, sounds like a setting is the way to go!

**Comment by dangwu** [comment]
@dozernz  I'm assuming you mean iPhone 8 Plus in landscape mode?

**Comment by dangwu** [comment]
Version 4.1.0 is out with the new setting! Might take some time for it to appear in the App Store.

**Comment by dozernz** [comment]
Yes iPhone 8 plus in landscape. I've got the updated version and it works nicely. Thank you very much!

**Comment by voiprodrigo** [comment]
Hi. Thanks for the new version, that was quick!

Just one bit, the pages opening in popup window instead of full screen, that you do not plan to revert for the original layout?

**Comment by benhj** [comment]
Thanks, keeping it simple and clear is much nicer and far less cluttered looking. 

Ben.

**Comment by dangwu** [comment]
> Hi. Thanks for the new version, that was quick!
> 
> Just one bit, the pages opening in popup window instead of full screen, that you do not plan to revert for the original layout?

Making this full screen again

**Comment by dangwu** [comment]
> Thanks, keeping it simple and clear is much nicer and far less cluttered looking.
> 
> Ben.

I'm guessing you haven't used a 11"+ iPad yet :)
