### ISSUE TITLE
Flagging stories by accident 

### ISSUE THREAD

**Issue by sinia** [dangwu/Octal#199]
In comments view hitting the flag story button  for objectionable content is too easy by accident. It's next to Favourite button!

Also, not obvious what the flag button does, I pressed it only to realize that this flagged the story I was reading. Pressed it second time hoping it would undo the action but no luck

I propose:
1. Please consider changing the interface to make accidental hitting of the flag button more difficult.
2. Also need to make it more obvious what that button does as there seems to be no way to undo this action afterwards

I think perhaps both problems could be fixed by a confirmation pop-up with text explaining what is about to happen?

**Comment by dangwu** [comment]
Good point. Will update

**Comment by dangwu** [comment]
4.1.2 adds a confirmation dialog
