### ISSUE TITLE
Add "super compact" mode that hides the domain so more stories fit on the page

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#2]
Excellent HN app! 👍 (it just replaced MiniHack on my home screen)
I wanted to share a few wish list items (I'm going to make a separate issue for each for clarity)

> Please add a "super compact" mode that hides the domain so more stories fit per page

**Comment by dangwu** [comment]
These are awesome feature requests! Thank you so much. They're all on my TODO list now, starting with the easiest ones.

**Comment by dangwu** [comment]
Added with today's v2.12.0!

**Comment by luckman212** [comment]
Thank you very much for adding this! I just want to report 2 things:

1. To me I can't tell the difference between "Compact" and "Minimal" - they both look the same. I think maybe something is wrong with the "Compact" mode maybe?

2. The way the slider is laid out feels backwards to me - sliding to the left I would expect to make the view more compact (smaller) in accordance with the font size slider.
