### ISSUE TITLE
[Bug] Pull to refresh on iPad loads first story

### ISSUE THREAD

**Issue by mttjj** [dangwu/Octal#200]
Ever since the 4.0.0 version pulling to refresh on iPad constantly loads the first item in the list. I’m running iPadOS 14.4.2 and Octal version 4.1.2. Anything else you need from me to troubleshoot? 
Video was too big for GitHub so I’ve uploaded it here: https://streamable.com/d0mli9

**Comment by dangwu** [comment]
I think this is a bug that happens if you have Story Destination set to
URL. Will fix ASAP! Thanks!

**Comment by dangwu** [comment]
Fixed with 4.1.3 released today
