### ISSUE TITLE
[Bug] Half grey bar appearing on status bar in landscape orientation 

### ISSUE THREAD

**Issue by Taxyovio** [dangwu/Octal#201]
When using the app in landscape on ipad, there’s a grey bar on the left side of the status bar, with a size corresponding to the status bar width in portrait orientation. See screenshot.
![IMG_3754](https://user-images.githubusercontent.com/38234151/113925431-ec6e8080-97e2-11eb-99b1-35e19570a33f.png)

**Comment by dangwu** [comment]
Do you have exact steps to reproduce this? I haven't been able to reproduce it myself.

**Comment by Taxyovio** [comment]
Just updated to 4.2.1 and I haven’t been able to reproduce either. 

The bar used to appear when you scroll down a bit after starting the app in portrait and then rotating to landscape. It could also be happening when starting in landscape but I couldn’t recall exactly.
