### ISSUE TITLE
GitHub favicon does not render in full/compact stories layout

### ISSUE THREAD

**Issue by soulseller** [dangwu/Octal#202]
Octal 4.3.0
iOS 14.4.2

**Comment by dangwu** [comment]
I'm guessing you have dark mode on? They're favicon isn't dark mode friendly. It'll be black on black

**Comment by luckman212** [comment]
I was going to say the same, kind of related to #197 - even with that new improved Blue it still feels a little off in dark mode. The contrast is just too low.

@dangwu If you ever play with the colors again, I suggest copying the shade that Apple uses for links in Mail.app in Dark mode. It's just slightly brighter/less saturated, but makes a difference.

**Comment by dangwu** [comment]
Can you send a screenshot of that?

**Comment by luckman212** [comment]
Sure - but I don't want to hijack @soulseller's issue. I'll post it on the other thread.

**Comment by soulseller** [comment]
GitHub favicon (https://github.com/favicon.ico) is changed with the default favicon (pixelated globe) regardless of the light/dark theme settings.

**Comment by dangwu** [comment]
I see what you mean now! Will investigate

**Comment by dangwu** [comment]
Turns out it's just coming up blank with google's favicon service: https://www.google.com/s2/favicons?domain=github.com

Closing, as they should fix it on their end and it's not a big deal
