### ISSUE TITLE
Duplicated favorited comments

### ISSUE THREAD

**Issue by quinncomendant** [dangwu/Octal#203]
Hello,

I just noticed comments on the Favorites screen is duplicated. Stories are not duplicated, only comments. I'm using Octal v4.3.0.

The duplication occurs immediately after favoriting:

1. Favorite a comment by selecting `…` → `Add to Favorites`
2. Navigate to User profile → favorites → Comments
3. The comment I favorited is listed twice.

![IMG_9712](https://user-images.githubusercontent.com/6884276/114288036-a3f8d200-9a31-11eb-8a75-0c819232d561.jpg)

**Comment by luckman212** [comment]
can confirm

**Comment by dangwu** [comment]
Thanks! Will fix
