### ISSUE TITLE
favorites not loading

### ISSUE THREAD

**Issue by mdcmos** [dangwu/Octal#204]
I have recently noticed favorites no longer load, all I see when accessing them is a frozen loading spinner icon.
In Settings > Account > Favorites
Latest version on iOS 14.4.2

btw really love Octal (I am a premium user), if I can suggest an improvement re. favorites, I think Favorites and Activity should both be an icon in the main app navigation at the bottom.

Thanks.

**Comment by dangwu** [comment]
I have a new version in review that addresses #203. It revamps favorites loading (which is really hacky HTML parsing), so it hopefully resolves this issue as well. I've seen it a while back, but not recently. You might be running into HN API limits. 

I actually already thought of adding Favorites/Activity as a tab bar icon. I think I will do that that at some point! Thanks!

**Comment by dangwu** [comment]
Let me know if this isn't fixed in 4.4.0 for you
