### ISSUE TITLE
After tapping links from a user profile, the text disappears

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#205]
This is a funny/strange one:

version 4.6.0

tap on either 
- your profile (account tab)
- or any profile by tapping someone's username

If they have any links in their profile / about section, and you click on one of those links, when you return from the browser, the text will quickly fade away & then disappear.

example:  before
![63CD3299-BE50-40C7-A28F-3D66494264F3](https://user-images.githubusercontent.com/1992842/115643543-f320eb80-a2ea-11eb-8bc2-5adbb529b193.jpeg)

after
![CE574520-A6A2-4255-9222-F2BCA356774E](https://user-images.githubusercontent.com/1992842/115643565-fddb8080-a2ea-11eb-9e45-9201b084e128.jpeg)

**Comment by dangwu** [comment]
Damn, good find! I'm glad this is seemingly your only issue this version :D

**Comment by dangwu** [comment]
Fix released!
