### ISSUE TITLE
Comments are sometimes replaced by unrelated hyperlink

### ISSUE THREAD

**Issue by Klohto** [dangwu/Octal#206]
Hello! Got the new update, looks great ☺️ Just noticed an issue with comments.

I've been browsing a recent Lichess post https://news.ycombinator.com/item?id=26910579 and some of the comments appear as hyperlinks. The URL redirects to unrelated link not present anywhere in the source comment (definitely posted somewhere in the comments though).

Scrolling past ~80% (on the same post) crashes the app as well.

![image](https://user-images.githubusercontent.com/6950876/115865840-296c8100-a439-11eb-8599-11889d5bba65.png)

![image](https://user-images.githubusercontent.com/6950876/115865856-2d989e80-a439-11eb-9be1-4d23ee13ac84.png)

iPhone 8, iOS 14.4.2

**Comment by dangwu** [comment]
Good find. I thought I fixed this with today's release but this Lichess post is crashing for me too. On it!

**Comment by dangwu** [comment]
Fix awaiting Apple review!

**Comment by Klohto** [comment]
Wow, amazing speed! 🙏

**Comment by dangwu** [comment]
I actually had the fix awaiting Apple review before you made this issue, haha. I didn't notice the crash though, so that's now awaiting Apple review.

**Comment by Klohto** [comment]
Confirming that crashes and hypertext comments are gone ✌️

**Comment by Klohto** [comment]
Nevermind, the comments are back.

![093B9C0F-8D0F-4DE5-9F4F-29ED8704E47A](https://user-images.githubusercontent.com/6950876/115946866-4732f800-a4c4-11eb-85d2-6b3c97d8e99d.png)

This time in the Minio thread https://news.ycombinator.com/item?id=26919510

They are shown on the first pass but looks like they disappear when I go further down and come back. Verified I’m at 4.7.1

**Comment by dangwu** [comment]
Ugh. On it. Thanks

**Comment by dangwu** [comment]
Should definitely be fixed now! Reopen if issue persists. Thanks!
