### ISSUE TITLE
Overwhelming haptics

### ISSUE THREAD

**Issue by vtrottier** [dangwu/Octal#207]
There are two scenarios where I find the haptics to be overwhelming:

1. When a story is clicked
2. When a comment thread is collapsed

These interactions happen very often and I think removing the haptics for them would result in a better user experience. Another option would be to add an option to disable haptics for the app, as recommended in [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/haptics/).

**Comment by dangwu** [comment]
Very true. I looked at other apps like reddit/apollo and they don't haptic this often. I'll probably remove the haptics for 1 and 2!

**Comment by vtrottier** [comment]
Awesome! After more investigation, please also consider removing haptics for the following interactions:
- Opening article/link
- Skipping to next comment thread

**Comment by dangwu** [comment]
I like the comment skip one so I'll probably leave it and lessen the intensity. Agreed on the opening links.

**Comment by dangwu** [comment]
Should be better now!
