### ISSUE TITLE
Octal Crashes when Story is selected.

### ISSUE THREAD

**Issue by Jcowwell** [dangwu/Octal#208]
On iPhone 11 Pro Max.

Here’s a video showing this in action: 
https://imgur.com/a/DI1GHnQ

**Comment by dangwu** [comment]
Sorry about this! I have the fix ready and awaiting Apple review.

**Comment by Jcowwell** [comment]
Ah bet bet. Btw I notice that the comment scroller button is absent on the iOS App but present on the iPadOS App. Is this intentional ?

**Comment by dangwu** [comment]
@Jcowwell Nope - you might have dragged it to somewhere off screen somehow... you'll have to uninstall and reinstall the app to restore it unfortunately. I'll have to add a reset button somewhere for that. Also, the crash should be resolved
