### ISSUE TITLE
Unwanted UI alert during launch

### ISSUE THREAD

**Issue by soulseller** [dangwu/Octal#209]
Success!
Hacker News requires you to post or comment at least once before your user profile is populated.

**Comment by dangwu** [comment]
Any more info?

**Comment by soulseller** [comment]
In order to reproduce it, you'd need to login with a newly created HN account.

**Comment by dangwu** [comment]
Oh ok. That’s expected to appear then

**Comment by dangwu** [comment]
Unless it appears more than once

**Comment by soulseller** [comment]
The alert is shown on each and every app launch.

**Comment by dangwu** [comment]
Thanks, I'll check it out and fix ASAP

**Comment by dangwu** [comment]
Fixed! Reopen if issue persists.
