### ISSUE TITLE
Sorting Mode Crash on iPad

### ISSUE THREAD

**Issue by ekoranek12** [dangwu/Octal#21]
Attempting to change the sort mode under “Search” in settings crashes the app:
![img_0005](https://user-images.githubusercontent.com/8239273/52156356-8196ed00-264d-11e9-9b0d-ce8b5970d341.jpeg)

On this phone this opens a `UIAlertViewController` with preferred style of  `.actionSheet`. This could be a potential cause for this crash. On iPads `UIAlertViewController` presented as an `.actionSheet` must be configured and presented in a popover.

Here is an example of remedying this issue: https://medium.com/@nickmeehan/actionsheet-popover-on-ipad-in-swift-5768dfa82094

**Comment by dangwu** [comment]
Whoops! Thanks for the report. Shows how much I use the app on an iPad :/

I have a fix in the pipeline coming up ASAP!

**Comment by dangwu** [comment]
Fixed in v2.10.0 released today.
