### ISSUE TITLE
[Feature request] Support for Open in Octal

### ISSUE THREAD

**Issue by quanganhdo** [dangwu/Octal#210]
It'd be great if Octal can be launched from Safari when viewing a HN thread.

**Comment by dangwu** [comment]
How would it work? Via Sharing to Octal?

**Comment by quanganhdo** [comment]
Yeah, like an action extension to launch Octal with the current HN discussion.

**Comment by jlongman** [comment]
https://www.icloud.com/shortcuts/e22979673496405d8e58f997c2765761
 This was my version.

**Comment by dangwu** [comment]
Duplicate of https://github.com/dangwu/Octal/issues/236

also there is now a share extension in 4.12
