### ISSUE TITLE
Documents & data taking too much space

### ISSUE THREAD

**Issue by olivergrabinski** [dangwu/Octal#211]
I notice that the app is taking over 500 MB on my iPhone. I cannot seem to find any option to clear this data.

![image](https://user-images.githubusercontent.com/20188437/116466473-d0ed1780-a86e-11eb-84b9-8afe7b31dec4.png)

I haven't tried reinstalling the app but sharing in case this is an actual issue.

**Comment by dangwu** [comment]
That's really strange. Shouldn't go over around 100MB. I'll have to look into this. Not seeing it on my device

**Comment by dangwu** [comment]
Interesting; I guess that makes sense - when you browse links in Octal via In-App Safari I guess all that website data counts towards Octal's usage. Thanks for investigating!
