### ISSUE TITLE
[Feature request] Octal appearing when searching Hacker News plus synonyms

### ISSUE THREAD

**Issue by antgly** [dangwu/Octal#212]
When searching in Spotlight on my iPhone, it's a bit annoying that Spotlight doesn't suggest Octal when I search Hacker News or news.ycombinator.com. I could make a PR for something like this, but I'm interesting in contributing more than in just this PR. I see tons of promise in this app.

For reasons, maybe we could use ycombinator, news.ycomb, or hn - essentially terms with community value that doesn't introduce legal issues.

**Comment by dangwu** [comment]
Added some support. Spotlight search typically isn't used for finding apps, but content within apps. Searching for Ycombinator or Hacker News should surface Octal now!
