### ISSUE TITLE
"Last Year Ago"

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#213]
Small nitpick here but when searching / viewing old posts, there's some funny wording going on for certain timeframes. Example:

![30C9A44A-A9D0-41B5-A735-2002BC0F5FC8](https://user-images.githubusercontent.com/1992842/117386656-47b09300-aeb5-11eb-9f06-bb9f56f47fc8.jpeg)

**Comment by luckman212** [comment]
1 more example

![DA45CEAB-7ACD-43D0-95D7-2BBE4BF421A8](https://user-images.githubusercontent.com/1992842/117386808-83e3f380-aeb5-11eb-893f-0e3dec572459.jpeg)

normal date in Safari view
![0A17F6EC-7715-4A30-A9D9-B2542EAA0CEC](https://user-images.githubusercontent.com/1992842/117386837-93fbd300-aeb5-11eb-9e41-654e1dad21e5.jpeg)

**Comment by dangwu** [comment]
ha - nice find!

**Comment by dangwu** [comment]
I'll update it to show the exact date like the website. That's much nicer.

**Comment by RajatArora08** [comment]
Saw "Last week ago" too :)

**Comment by dangwu** [comment]
Fixed!
