### ISSUE TITLE
Split-View: when viewing an post rotating goes back to list on iPhone 11

### ISSUE THREAD

**Issue by kule** [dangwu/Octal#214]
On an iPhone 11 - If you view an post in portrait, rotate to landscape (goes into split-view) and rotate back to portrait (goes back to single column view) you end up back on the list view and lose where you were in the post comments.

I’ve turned off split view to get around this but thought I’d mention as it’s feels broken at the mo.

**Comment by dangwu** [comment]
Yeah that's broken. Do you actually *like* split view on iPhones? Wondering if disabling it on iPhones is the way to go.

**Comment by kule** [comment]
It’s kinda nice in landscape mode, but honestly I very rarely view it in that orientation.

I was more hitting this issue when reading something and perhaps putting my arm down and iOS putting it into landscape mode and when I raised my arm it flipped back to the default portrait mode but then “lost” where I was in the post.

Personally I don’t think you’d lose anything by just disabling the setting on iPhones.
