### ISSUE TITLE
Scottish Cafe

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#219]
Noticed something weird tonight while browsing HN in Octal

This story had no story link shown, it looks like a parsing error somehow. The HN link worked ok. Share story link just did nothing.

Here's the HN link:
https://news.ycombinator.com/item?id=27329131

![D4AF0CA6-9E5A-49F2-B224-7CB310C9F812](https://user-images.githubusercontent.com/1992842/120579239-2cbe3980-c3f5-11eb-8a7c-e05219ced2d0.jpeg)

**Comment by luckman212** [comment]
App ver 4.9.0

**Comment by dangwu** [comment]
Probably a data issue with the API. Will investigate!
