### ISSUE TITLE
Include an Acknowledgments section

### ISSUE THREAD

**Issue by glauberlima** [dangwu/Octal#22]
This is a very common and welcomed practice to say thank you for the open source libs' authors you have used within your app.

Take a look at some apps installed in your phone for examples.

Octal is the best HN client I have ever used. 

Thanks.

**Comment by dangwu** [comment]
I do have a "Thank You" section in the Help and Privacy link from Settings. You're right though, I should add an explicit section. Will work on it!

**Comment by dangwu** [comment]
And thanks for the kind words!

**Comment by dangwu** [comment]
Added!
