### ISSUE TITLE
Unvote / Undown not actually unvoting

### ISSUE THREAD

**Issue by jmiserez** [dangwu/Octal#225]
Changing a comment vote does not seem to work within the app. Even though Octal shows the change, it does not actually happen on HN. I can do these actions successfully in a regular web browser and have the required amount of Karma so it's not an account issue. This is with Octal Premium activated.

Steps to reproduce:
- Upvote any comment
- View in Web Browser, see that it is now upvoted
- Undo the upvote in Octal
- View in Web Browser, comment remains upvoted

The same issue happens with downvote+undown or upvote+downvote. In both cases, only the first action is actually done on HN, contrary to what the app shows.

Any ideas?

**Comment by dangwu** [comment]
Thanks for the report - I'll need to fix this. Something must've changed
with the API.

**Comment by dangwu** [comment]
Actually - can you try again? You might have just been blocked by the API
for doing things too quickly. Octal doesn't handle this error gracefully,
which I should still fix.

**Comment by jmiserez** [comment]
Only partially. Substitute 15s below for a higher number if HN is under load. I tried the following:

- Upvote, wait 15s, unvote, wait 15s -> OK
- Downvote/undown -> same
- Upvote, wait 15s, downvote, wait 15s -> NOK, the comment is still upvoted. Trying to undo the downvote in Octal gives the "Can't remove downvote" issue. If you don't wait long enough, the message box won't appear but the end result is the same.
- Downvote, then upvote -> NOK, same but with "Can't remove upvote" message.

Also in the first case, if you unvote too quickly then it can be "fixed" by upvoting, waiting 15s, then unvoting and waiting. But there's no indication in Octal that it's necessary.

But the upvote->downvote state is not fixable anymore.

The HN page in the browser isn't perfect either, as it won't register your vote if you navigate away too quickly. But there you can just reload the page and it will show the correct state. Reloading the thread in Octal doesn't do the same, it will still show the wrong state.

Maybe you could just refetch the vote states when reloading the thread? But the message box is probably a bug.

**Comment by dangwu** [comment]
Let me know if this is still an issue for you. It's been a while and I fixed a related issue a while back
