### ISSUE TITLE
"Show" panel is displaying "Top" view

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#23]
This was on 2.9.0 on iPhoneXS

I should have taken a screenshot, but shortly after updating to 2.9.0, and after fiddling around with the new filters, I noticed the "Show" tab was displaying the wrong stories. It was instead showing a replica of the leftmost tab (Top/Best/New) — even including the filter widget at the top. Pulling to refresh didn't help, but force-quitting the app and then re-launching it did. Now I'm having trouble reproducing this. Maybe some cache etc didn't get cleaned up after the upgrade. If it happens again I'll post more detail.

**Comment by dangwu** [comment]
Scary bug :/ 
I've been trying to reproduce this for a while and haven't had any luck. I'll keep an eye out for it!

**Comment by luckman212** [comment]
I figured out how to reproduce this. It's pretty simple actually.

1. Tap to switch to the "Show" section.
2. Exit the app.
3. Go back into the app.
4. You'll see now that the "Show" section has the little settings widget at the top.
5. Tap the widget and enter in a nuber e.g. "min 10 comments" or simply tap "Reset"
6. The view refreshes- but now you've got the wrong stories showing (screenshots below)

The only way to "fix" it now is to force-close the app.

![img_9213_33](https://user-images.githubusercontent.com/1992842/52177982-9d59da80-2796-11e9-962a-87f7af7877d6.PNG)

![img_9214_33](https://user-images.githubusercontent.com/1992842/52177994-aea2e700-2796-11e9-9225-dd064bfa72f5.PNG)

![img_9215_33](https://user-images.githubusercontent.com/1992842/52177998-b5315e80-2796-11e9-9235-a9eba9c3e6a0.PNG)

**Comment by luckman212** [comment]
This is great news. Thank you for your amazing work.

**Comment by dangwu** [comment]
2.10.0 is out. Thanks again for the find and excellent repro steps!

**Comment by luckman212** [comment]
Fix confirmed, and filters on all views are working. Excellent!
