### ISSUE TITLE
Tap target for comments in Minimal view too small

### ISSUE THREAD

**Issue by zmilonas** [dangwu/Octal#233]
Hey,

loving you app,
I like using the minimal view for stories on my iphone 12 mini but find the tap target of the small comment icon on the list view to small to navigate to the comment section. 

I have a toggle set to navigate to url when clicking on a story but I often want to also see the comments.

Could you please either include a bigger comment button on the right hand side or some alternative way to get to them? I have to often click several times before i manage to hit the comment button, i usually fatfinger into the URL destination.

I use font size 13

![image](https://user-images.githubusercontent.com/25948390/136571047-adc2f25c-f46d-4750-9960-db413a5f1dcd.jpeg)

My settings:

![image](https://user-images.githubusercontent.com/25948390/136571132-54e18016-24c8-453b-9484-6661ee0ce861.jpeg)

**Comment by wezm** [comment]
My settings are similar except I'm using the Compact layout. I wanted to echo my support for this issue but add that it would be great if the tap target for the upvote button was bigger also. Hitting that, like the comment button often requires multiple attempts before getting one that doesn't trigger viewing the link.

**Comment by ahuse** [comment]
Bigger buttons would be awesome. 

Otherwise, great app!

**Comment by dangwu** [comment]
Slightly increased tap targets - let me know if it's still too small
