### ISSUE TITLE
Bug - account screens not updating

### ISSUE THREAD

**Issue by iakovmarkov** [dangwu/Octal#234]
After leaving a few comments earlier today, I wanted to check replies from Account -> Activity screen. The comments were not there, even after refreshing (dragging the screen down until spinner showed up) a few times.

When I opened an older comment and clicked on my profile, I was able to see my latest comments and even updated karma count.

This is a pretty major bug in my opinion.

**Comment by dangwu** [comment]
This is almost guaranteed to be a bug/delay/outage with HN services. Let me
know if it persists

**Comment by dangwu** [comment]
My plan is to migrate away from using the Firebase SDK/API. I'm forced to use a really old version and it's not very performant or reliable. This should solve any issues like these as well. I don't have a good ETA for this, but hopefully by the end of the year. Sorry for the issues!

**Comment by dangwu** [comment]
I reproduced this today (while fixing the upvoting issue) and believe I found a fix for this! Stand by!

**Comment by dangwu** [comment]
Fix is out
