### ISSUE TITLE
[BUG] Can't restore premium purchase w/ Family Sharing enabled

### ISSUE THREAD

**Issue by MichaelVangard** [dangwu/Octal#237]
I'm not sure if I misunderstood what I was buying when I unlocked premium, I assumed that meant I'd be able to use it with Family Sharing enabled. When I try to restore the premium purchase on an account within my Apple family, it just hangs and doesn't unlock.

**Comment by dangwu** [comment]
I just enabled Family Sharing - it defaulted to off. Please try again in a few hours! Thanks

**Comment by MichaelVangard** [comment]
Thanks Daniel!

**Comment by dangwu** [comment]
@MichaelVangard  did it work for you?

**Comment by MichaelVangard** [comment]
Thanks for following up.

Still isn't working for me. 

I get a couple dots going back and forth after hitting the restore button, but it just keeps doing that. If I tap again it'll prompt me for the double-click to buy premium or it'll sometimes say "Something went wrong. Please try again later."

**Comment by dangwu** [comment]
Darn, no problem. Someone else also said it didn't work so I think I have to make an app update and support it. Will track with #239
