### ISSUE TITLE
Support Family Sharing of Premium

### ISSUE THREAD

**Issue by markontiva** [dangwu/Octal#239]
The app page used to say it supported Family Sharing, but that seems to have disappeared. I have a personal iPad/iPhone and a family iPad w/ separate Apple ID that is a part of our Apple family group. Would be great to be able to activate my premium purchase on the family iPad too. This works great for apps like Apollo, so I would really love it if Octal supported this sharing of one-time in-app purchases too.

**Comment by dangwu** [comment]
I enabled Family Sharing for Premium yesterday. I just checked and confirmed that it is on. It wasn't on before yesterday.

**Comment by markontiva** [comment]
Interesting. The app page definitely displayed that it was compatible with family sharing prior to yesterday, but maybe that didn't apply to the premium in-app purchase. Not sure what it was referring to then since the app is free without in-app purchase. Since yesterday, the family sharing indicator disappeared from the app page when viewed on an iPhone, but does show when viewed in Safari on a Mac.

**Comment by markontiva** [comment]
Tried restoring again today and family sharing still isn't working. I went ahead and repurchased it on my other account but it'd be great if you could get this working.

**Comment by dangwu** [comment]
Damn, I guess it doesn't work w/o code changes. I'll have to work on this.

**Comment by MichaelVangard** [comment]
Just tried to unlock premium through family sharing again and this time it worked!

**Comment by dangwu** [comment]
Ohh good to know! Thanks!
