### ISSUE TITLE
Upvotes fail

### ISSUE THREAD

**Issue by nperanzi** [dangwu/Octal#240]
Attempting to upvote a post or comment fails, with different error messages (one for posts, one for stories). I am able to upvote using other iOS clients or through a web browser. 

Error message when attempting to upvote a post from the front page list of posts:
**Can't remove upvote**
Too much time has passed since upvoting

Error message when attempting to upvote a comment from the discussion of a post, or the post itself from the discussion page:
**Something went wrong**
Please try again later

![Error on front page](https://user-images.githubusercontent.com/7450800/142334999-97cc2765-5427-44d4-bcdf-bcd29e6889d4.png)

![Error on post discussion](https://user-images.githubusercontent.com/7450800/142335008-3a7c1f2b-d31f-494c-bb58-912a065ae90d.png)

**Comment by nperanzi** [comment]
I'm on an iPhone 12 Pro Max running iOS 15.1. Octal version is 4.10.1

I have tried logging out and back in, then uninstalling and reinstalling, neither of which resolved the issue.

**Comment by dangwu** [comment]
Thanjs - working on it! Looks like HN changed their inner workings a bit so
it broke stuff

**Comment by nperanzi** [comment]
Awesome, thanks for jumping on it so quickly!

**Comment by dangwu** [comment]
Of course! Fix is pending Apple review.

**Comment by dangwu** [comment]
Fix is live!

**Comment by nperanzi** [comment]
Phenomenal - confirming all is working as intended. Thank you!
