### ISSUE TITLE
Cannot upvote comments or favorite a story

### ISSUE THREAD

**Issue by leobaumgardt** [dangwu/Octal#241]
Since a few days ago, I can no longer upload comments or favorite a story. Also, when I go to “profile” and select to display content that I have liked, the page is empty.

I already tried closing the app and we starting it, as well as logging out and logging back in again. Both did not help. I am also on the newest version.

**Comment by dangwu** [comment]
Upvoting isn’t working for you? I’ll need to fix favoriting. Thanks for
letting me know!

**Comment by leobaumgardt** [comment]
Yeah. I have to open the story or comment in Safari to be able to fav/upvote. It used to work without problems until a while ago. Maybe 2-3 weeks ago. Also, I suspect that some of my comments might not be sent. I’m not sure about that one though. The fact that it doesn’t show any likes or favorites in my account makes me think that something in the communication with HN is broken. Let me know if you need more details, screenshots, or anything like that. Thanks!

**Comment by dangwu** [comment]
Are you sure upvoting is still broken for you with the latest update
4.10.2? That fixed it for me and seemingly everyone else

**Comment by leobaumgardt** [comment]
Thanks for looking into this.

I just checked. Hadn’t seen that you posted another update 3 days ago. I just installed it and it fixed most of the issues:

✅ Favorite a story
✅ Upvote a comment
✅ See all my comments under Account > Activity

One thing still seems broken:

❌ See my favs under Account > Favorites

That one still shows empty.

**Comment by dangwu** [comment]
Awesome! That fix for viewing favorites is coming soon!

**Comment by dangwu** [comment]
Favorites fixed!
