### ISSUE TITLE
Account tab is empty

### ISSUE THREAD

**Issue by sherwinski** [dangwu/Octal#242]
Thanks for such a great app - as a premium user I'm loving it so far.

When I press on the Account tab I am met with an empty screen, my username is displayed at the top with an option to Sign out. I'm not entirely sure what I am expecting to see on this tab but judging from other opened issues there should be some content on there. More specifically, I've very interested in a way to access my favorited posts. I have tried shutting down/restarting the app as well as signing out and back in with no luck.

App version 4.10.2 on iOS 15.1

**Comment by dangwu** [comment]
Have you posted any comments or submitted any links yet? The API returns an empty user if you haven't!

**Comment by pvandebelt** [comment]
I’m having the same issue. Account tab is empty. All my favorited stories disappeared. 

When I favorite a story currently, the story doesn’t appear on the account tab either.

**Comment by sherwinski** [comment]
@dangwu ah I had not, but after submitting one I see that it now works! Thanks for the quick response 🎉
