### ISSUE TITLE
Bug: “Share HN Link” copies title instead of URL

### ISSUE THREAD

**Issue by leoplusx** [dangwu/Octal#243]
I just wanted to use the “Share HN link“ to copy the URL to the story I was reading to the clipboard. What was copied to the clipboard instead was the title of the story. This seems to be a bug.

**Comment by dangwu** [comment]
It should copy the title and the URL. Which story was it?

**Comment by leobaumgardt** [comment]
Any story, really. 

I tap the share symbol. I tap “Share HN Link”. I tap “Copy”. And then my clipboard looks like this:

“Apple Broke Up with Me”

(I just took the top front page story now for demonstration.)

The same happens when I, in the share menu, select another app as the target.

I would’ve recorded a screencast, but I can’t seem to upload video here.

**Comment by dangwu** [comment]
Weird - I don't have this issue at all. Both the title and the URL should
be copied.

**Comment by dhruhin** [comment]
When copying it to some other apps (Notion for me), it only copies the story Title when I hit Share (share sheet opens) and Copy.

**Comment by 6e622dafdae9** [comment]
This also happens in Signal messenger. Steps to repro:
1. Go to any story.
2. Click share for the main store, or any comment. Tap "Share HN link"
3. In the share sheet, tap "copy" (Note: do not share to any app directly here).
4. Go to Signal messenger.
5. Double tap the text entry field, and select "Paste"
The title of the story shows up, not the URL.

Strangely enough, if I go to the iOS Notes app and repeat step 5, the title and URL are both pasted. Which character is used for the line break between the title and URL? Is something funny happening there?

**Comment by bfelbo** [comment]
This also happens when trying to share links to comments.

**Comment by timpulver** [comment]
Any news on this? This happens with all links. I always need to open the HN page in Safari and copy it from there as a workaround.

Example:
- Navigate to any HN article (not Share HN or similar)
- Click on Share -> Share HN Link
- Paste in any editor. I paste it here:

Bandcamp has been sold to Songtradr. What does this mean for the musicians?

What I would expect instead
https://news.ycombinator.com/item?id=37695035

The above contains the title, but not the URL. I wish it would copy the URL, and just the URL (no title).

**Comment by dangwu** [comment]
I still can’t repro this. I get this:

Visual Node Graph with ImGui
https://news.ycombinator.com/item?id=37702059

Can you send a video?

**Comment by dangwu** [comment]
Bandcamp has been sold to Songtradr. What does this mean for the musicians?
https://news.ycombinator.com/item?id=37695035

**Comment by dangwu** [comment]
https://github.com/dangwu/Octal/assets/5155951/56fdc454-c521-42c0-bcea-4201c533b03e

**Comment by dangwu** [comment]
Regardless, I can just make it copy the URL only…. Stand by

**Comment by timpulver** [comment]
Here is a video of the issue:

https://github.com/dangwu/Octal/assets/1055819/e402b972-dbe4-436b-b8ac-33f9783576b5

**Comment by dangwu** [comment]
Fixed in 4.15.1
