### ISSUE TITLE
Links missing in show HN posts

### ISSUE THREAD

**Issue by sbdchd** [dangwu/Octal#249]
it seems links in show HN style posts are broken. The fav icon shows up but there isn’t any link to click.

![B44F2A8D-4B57-4314-AF25-89BEB095EDB0](https://user-images.githubusercontent.com/7340772/153979328-7d6c4a64-cbdc-4fa4-a71b-9f9b87ad20bd.png)

Thanks!

**Comment by luckman212** [comment]
I came to report the same. @dangwu hope you can find a little time to work on this one! For now I'm opening them in Safari so I can get to the link...

**Comment by dangwu** [comment]
Sorry - I’ve been meaning to get around to this! Definitely on my radar.

**Comment by dangwu** [comment]
Fixed!

**Comment by luckman212** [comment]
@dangwu thanks for fixing this! But there might be 1 more small tweak needed. There's some kind of overlap happening on certain posts. Not sure what's causing it (missing favicon or something?)

e.g. 

https://news.ycombinator.com/item?id=30732147

![E7F47ACE-BADE-40E3-A1B6-407BB6B90357](https://user-images.githubusercontent.com/1992842/159168766-e6c79421-22a9-41e1-8381-ac994655e06a.jpeg)

**Comment by dangwu** [comment]
Oof. Will fix!
