### ISSUE TITLE
Filter settings lost after crash

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#25]
Version: 2.9.1

Today after updating to 2.9.1, I got a crash when launching Octal. I had used it for about 20 minutes and then switched to another app. 

When I went back into Octal, it crashed immediately upon launch. I launched again and it didn't crash, but I noticed the filter settings I had applied were back to default (0).

To test this, I entered some filter settings and then force quit the app. When I went back in, the filters were again reset back to 0.

**Comment by luckman212** [comment]
Actually after additional usage, I realize that these settings are lost/reset even after a "normal" app close once a certain period of time has elapsed and the view or cache gets stale. 

E.g. Set the filter to Min. Points = 50 and then exit Octal. Wait ~1 hour and then re-launch it. The filter is gone, back to 0.

**Comment by luckman212** [comment]
Ok. I understand now. Yes, remembering the filter settings between sessions would be great! If you are open to one more suggestion:

When tapping on the numeric fields to set the filter values, it's sometimes tricky. For example, if there is a **0** in there, when tapping and then typing a **5** you often end up with **50** since the 0 is not erased.

It would be good if, when tapping on the number, the field contents were highlighted so that the new value overwrites the old one when typed.

**Comment by luckman212** [comment]
I just got the 2.11.1 update and see you implemented the "clear field on select" -- thank you!

**Comment by dangwu** [comment]
Yup! Persistent filters are coming soon.

**Comment by dangwu** [comment]
Added with today's v2.12.0!
