### ISSUE TITLE
iPad - landscape layout looks weird

### ISSUE THREAD

**Issue by iakovmarkov** [dangwu/Octal#251]
Hello again @dangwu.
I’ve installed Octal on my new iPad Air 5th gen. There is a weird layout bug when using Octal in landscape: [https://imgur.com/a/QGBLzYp](https://imgur.com/a/QGBLzYp). See the gray bars on the left and right of content? That’s what I mean.

**Comment by dangwu** [comment]
I see it. Is that new or has it changed?

**Comment by iakovmarkov** [comment]
I don’t know, this is my first iPad :)

**Comment by dangwu** [comment]
Fixed!

**Comment by iakovmarkov** [comment]
Great, thank you!
