### ISSUE TITLE
Favourites don't work on Mac

### ISSUE THREAD

**Issue by Bobthe3** [dangwu/Octal#252]
When saving/favorite a comment or article on the Mac Version of Octal the app does not recognize this and save the article for later use.

**Comment by PsukheDelos** [comment]
I have a similar issue on iOS which I think may explain what you are seeing @Bobthe3. 

I can tap to save a comment and there is a banner that indicates this has happened. 

![image](https://user-images.githubusercontent.com/2417969/168506301-9e9f7f96-b50c-4cb8-a4a5-13e281c032ea.jpeg)

Then I navigate to Account > Favorites > Comments. But this does not display my favorited comments. 

![image](https://user-images.githubusercontent.com/2417969/168506349-e66e72e5-8675-40ec-8da2-153eb3fe23cc.jpeg)

However, if I log into HN via the standard website I can see that comment has in fact been favorited and saves to my HN profile. 

![image](https://user-images.githubusercontent.com/2417969/168506403-a98a573c-8fd9-4290-aac8-7153f0c2ea11.jpeg)

@Bobthe3 can you check if your favorited comments are accessible via the HN website please? I'd like to confirm if we're having the same issue or if what I'm seeing is specific to iOS. Thanks!

**Comment by dangwu** [comment]
Thanks for the reports. I’m also seeing favorite comments not working. HN
seems to keep changing their HTML so this keeps breaking. Will fix when I
get time!

**Comment by quinncomendant** [comment]
There's a mac version of Octal‽ I want! Where?

**Comment by dangwu** [comment]
This was fixed a while ago!
