### ISSUE TITLE
Horizontal layout does not respect notch

### ISSUE THREAD

**Issue by mbuczko** [dangwu/Octal#255]
First of all, thanks for the app - it's brilliant piece of work. 

One problem I found is that on iPhone 12/13 rotating device into horizontal ("landscape") position hides side part of view behind notch, which makes reading uncomfortable. The other issue is no way to get to the bookmarked items, but seems like it's been already reported.

**Comment by dangwu** [comment]
Hey there! Which part of the view is hidden behind the notch in landscape mode?

Also when you say `no way to get to the bookmarked items`, do you mean Favorites? That should just be accessed from the `Account` bottom tab, then `Favorites`

**Comment by mbuczko** [comment]
hey @dangwu, thanks for response.

here is the screenshot which explains the problem with partially hidden view:
![IMG_0631](https://user-images.githubusercontent.com/586537/185636011-4b6fbaec-8463-4bb4-a481-ac3210653862.jpg)

btw. landscape mode also behaves a bit inconsistent on scrolling. here is an initial view:

![signal-2022-08-19-161501_003](https://user-images.githubusercontent.com/586537/185638302-9e5dff40-4368-4036-b8a0-f59aee70bf66.jpeg)

and here is how it changes when scrolling starts (note the indentation left side):

![signal-2022-08-19-161501_002](https://user-images.githubusercontent.com/586537/185638398-d3c140d5-bb89-4c15-aa34-dc30a9d7cf60.jpeg)


talking about bookmarked items - yes, I meant favourites. For some reason my `Account` tab remained totally empty after initial sign-in. It took a couple of minutes before it got filled in with account details and "favourites" item. I noticed that after creating a ticket, sorry for raising a noise - it's no longer a problem.

**Comment by dangwu** [comment]
Thanks for the screenshots. I see it now!

**Comment by dangwu** [comment]
Fixed!
