### ISSUE TITLE
Detect when comments have been disabled

### ISSUE THREAD

**Issue by kkirsche** [dangwu/Octal#256]
This issue is to detect and prevent attempts to submit a new comment when replying has been disabled due to elapsed time since the post.

This would provide a more clear message to the user rather than an Oops something went wrong message when attempting to comment on a disabled thread.

**Comment by dangwu** [comment]
Pretty good idea. Any idea what the exact time is? Parsing HTML to detect the error is a no-go

**Comment by kkirsche** [comment]
It sounds like two weeks per https://news.ycombinator.com/newsfaq.html which says:

> Why can't I post a comment to a thread?
>
> Threads are closed to new comments after two weeks, or if the submission has been killed by software, moderators, or user flags.

**Comment by dangwu** [comment]
Thanks!

**Comment by dangwu** [comment]
Fixed a while ago
