### ISSUE TITLE
Upvotes not working

### ISSUE THREAD

**Issue by orf** [dangwu/Octal#257]
Hey,
I love Octal, but I've noticed that upvotes/downvotes are not working correctly. If I upvote someone in the app I can see that it is persistent - if I re-load the thread after closing the app the votes are marked as counted.

However if I log into HN website, the comments do not have my votes reflected on them.

**Comment by dangwu** [comment]
Thanks, I'll take a look soon. Looks like upvoting comments is working
properly but something changed with submissions.

**Comment by dangwu** [comment]
Seems to be working now. Probably a backend issue with HN> Let me know if
the issue persists for you
