### ISSUE TITLE
Tap to collapse comments

### ISSUE THREAD

**Issue by kcmannem** [dangwu/Octal#26]
I know there’s a next comment button but it’s in such an uncomfortable position that i don’t use it. I’d be ok with custom positioning for that button or let us collapse comments on tap, this makes it easier to traverse a thread as well.

**Comment by dangwu** [comment]
You can tap to collapse comments but tapping them at the top header area (next to author name and timestamp). Does that resolve your issue?

**Comment by dangwu** [comment]
That's fair. I do think an optional 'tap anywhere to collapse' and/or ability to set a custom position for the next common button are good ideas. I'll keep this open for those purpose. Thanks!

P.S. If you aren't aware you can swipe left on a comment to collapse it.

**Comment by dangwu** [comment]
'Tap anywhere to collapse comments' is added with today's v2.11.1 release. Thanks for the idea! I have no idea why I never thought of it before - I was just so used to tapping the headers.
