### ISSUE TITLE
What API do you call?

### ISSUE THREAD

**Issue by ibeckermayer** [dangwu/Octal#263]
Hey, love the app, but also am an information junkie and am experimenting with https://freedom.to/ to help me curb my addiction. I've added ycombinator.com to my blocklist and it blocks hacker news in my browser, but Octal still seems to work. I imagine you're calling some proxy address with the app, can you tell me what it is so I can block it?

**Comment by dangwu** [comment]
Octal uses the firebase api at
https://hacker-news.firebaseio.com
