### ISSUE TITLE
Comments touch target in "minimal" layout is infuriatingly small

### ISSUE THREAD

**Issue by jasongill** [dangwu/Octal#270]
I love Octal but have found that getting to the comments when using the "layout: minimal" and "story destination: URL" settings is infuriating. The touch target for the comments is very hard to tap, and takes multiple attempts to hit. I just screen recorded myself trying to get to the comments for a story and it took 6 attempts.

Is it possible to make the touch target bigger in the list view, and/or to add a "comments" button on the story view? Worst case, even a link to the comments in the "aA" button that has options for review view would be helpful.

Thanks for a great app!

**Comment by dangwu** [comment]
Could definitely be easier to tap. Adding to my to do list!
