### ISSUE TITLE
Bug: Comment Jump Button Barely Visible

### ISSUE THREAD

**Issue by Skates1616** [dangwu/Octal#272]
The comment jump button has nearly disappeared recently:

![image](https://user-images.githubusercontent.com/23196661/233391937-586ab91c-8aaf-475c-a511-f709cda04b43.png)

Refer to attached photo.

**Comment by dangwu** [comment]
You have to long press it and drag it wherever you want. Unfortunately if you get it stuck somehow you have to reinstall the app to reset its position
