### ISSUE TITLE
Requesting access to local network

### ISSUE THREAD

**Issue by taylorhakes** [dangwu/Octal#273]
I just got a notification that Octal is requesting access to the local network. Why is it requested?

**Comment by dangwu** [comment]
I have a suspicion that the Firebase SDK I’m using is doing it; but need to
confirm. Octal is not doing anything special to request it.

**Comment by dgpokl** [comment]
I had this happen too, and I had a SafariWebView sheet in the foreground at the time it happened, so I wonder if something happening in the webview could have triggered this.

**Comment by p-rintz** [comment]
This seems to still be an issue on my side. 

I have had this happen thrice on my iPhone yesterday.
