### ISSUE TITLE
Add some way to open HN link in Octal

### ISSUE THREAD

**Issue by msridhar** [dangwu/Octal#274]
Love the Octal app!  It'd be great if from a https://news.ycombinator.com link inside Mobile Safari, I could easily open the same page inside Octal.  The flow could be something like Share -> Open in Octal.  Or maybe Octal could provide an option to register itself so that HN links by default open in Octal?  Sorry if this feature already exists and I missed it.

**Comment by dangwu** [comment]
Thanks for reaching out. I do want to add a share extension when I have
time!

**Comment by dangwu** [comment]
Will be included in the next release as a Share extension
