### ISSUE TITLE
Comment Jump Button disappeared

### ISSUE THREAD

**Issue by seaty6** [dangwu/Octal#276]
I think I may have accidentally dragged the button off screen, but now toggling the switch does not bring the button back. Is there a way to reset the position of the button without resetting all app data?

**Comment by dangwu** [comment]
Unfortunately you need to reinstall the app to reset the position. I can add a reset option later

**Comment by seaty6** [comment]
Can fix without reinstall by rotating phone - the button will reappear.

**Comment by dangwu** [comment]
You can turn it off and on in settings to reset its position
