### ISSUE TITLE
More actions on comments

### ISSUE THREAD

**Issue by ishitatsuyuki** [dangwu/Octal#28]
Since the collapse functionality is now achieved with a tap, there's probably no use of the swipe menu on comments.

Instead, actions like upvote or reply could be it that menu.

**Comment by dangwu** [comment]
Very true. I meant to do this but forgot. Switching comment swipe action to 'upvote' in the next version, coming out tomorrow. Thanks!

**Comment by ishitatsuyuki** [comment]
Received update. Closing.
