### ISSUE TITLE
[FEATURE] Swipe to comments

### ISSUE THREAD

**Issue by zmilonas** [dangwu/Octal#280]
Hey,
so back in the day I reported the comment tap target being a little small and you made it larger, thank you! I still occasionally find it difficult to click the comment icon so i'd love to be able for the swipe the motion on a story to go to comments for it instead of switching to other panes (Ask HN etc)
Kind of like email clients have swipe to archive. Would that be possible?

Thanks!

**Comment by dangwu** [comment]
That wouldn't gel with the existing horizontal swipe between filters (top, best, new, etc), so it's a no go. Did you know you can change the story destination to comments in the settings?
