### ISSUE TITLE
New design makes it hard to click to article

### ISSUE THREAD

**Issue by jackbrannen** [dangwu/Octal#283]
Hey I use Octal every day and really like it. Thanks for the great app. 

A recent release changed the design of the main list view so that not all articles had thumbnails and the few that did moved the thumbnails to the right. I’m now finding it nearly impossible to click the article links from this view. The tap target is a small blue line of text only, and I almost always miss and go into the comments instead. Am I missing something? This seems like an oversight. 

Thanks!
Jack

**Comment by jackbrannen** [comment]
Thanks, but that just reverses the problem. Now it's hard to get to the comments. The issue is the small tap targets.

**Comment by dangwu** [comment]
Gotcha. Let me work on increasing tap target sizes.

**Comment by jackbrannen** [comment]
Truthfully I thought the prior version was perfect, since each row had a thumbnail icon that you could click to get to the article or the rest of the row you could click to get to the comments. 

The new design works well enough if an article has a thumbnail icon. But not all of them do anymore. I think if you just brought them all back you’d be golden.

**Comment by dangwu** [comment]
Fair point. You’re the second to say this too. Let me rethink it.

**Comment by youens** [comment]
I came here to say the same thing. 😊 I love the app and use it dozens of times a day. I typically have to try a few times to open comments (with my default setting to open the link). Perhaps it's fat fingers. 😅

**Comment by dangwu** [comment]
Let me know if it's still hard to click

**Comment by youens** [comment]
Not at all, it's easy now! Thanks so much.
