### ISSUE TITLE
Difficult to reliably tap to comments in minimal mode

### ISSUE THREAD

**Issue by youens** [dangwu/Octal#284]
I love this app, and use it dozens of times a day! 

That said, when in "minimal" mode, and with the default _Story Destination_ set to URL, the touch target to view comments seems nearly impossible to reliably tap.

Sometimes I find myself trying several times back and forth until I get it... no matter how hard I focus on placing my sausage fingers on the right place. 😅

Perhaps I'm missing an obvious technique or setting? If not, then maybe there's some way to make the two action tap regions more distinct?

Again, love the app! Thanks for the hard work!

![image](https://github.com/dangwu/Octal/assets/227123/dc3b974b-d50b-4d98-9721-7347a1a87a21)

**Comment by dangwu** [comment]
Made tap area much bigger
