### ISSUE TITLE
Crash and lockup on iOS 17

### ISSUE THREAD

**Issue by fiznool** [dangwu/Octal#288]
This is very anecdotal but since I upgraded to iOS 17, twice now when using Octal, it has crashed, and subsequently my phone becomes unresponsive - sitting on the main iPhone Home Screen, not responding to taps or button presses. 

The first time this happened, I was reading an article in Octal's in-app browser. The second time was from a comment thread. 

I'm running iOS 17.0.1 and the latest version of Octal at the time of writing.

**Comment by dangwu** [comment]
Is this still happening for you?

**Comment by fiznool** [comment]
No I haven't noticed it for a week or two now. Feel free to close! I can always reopen if I see it again.

**Comment by dangwu** [comment]
Thanks
