### ISSUE TITLE
Mark post/comment as upvoted

### ISSUE THREAD

**Issue by darsnack** [dangwu/Octal#29]
It would be nice to have a visual indicator on each post/comment that we have already upvoted.

**Comment by dangwu** [comment]
Definitely planning to add this. I currently show upvote arrow and score as orange if it was upvoted in the current app session. It's not easy to persist across sessions because there's no API for fetching this data. Have to parse HTML from the HN website.

**Comment by darsnack** [comment]
Some kind of circular buffer of comment/post IDs stored locally on device might be sufficient since HN content changes fast enough. For items that leave the buffer, you could gracefully add the upvote color when the user attempts to upvote and an error is returned (I don't know if you are able to discern between errors due to already upvoted and other errors).

Not as complete as parsing the HTML would yield, but it is easier to implement (maybe?).

**Comment by dangwu** [comment]
Yup, that's a good option too, but it would be a poor experience for people who upvote from the web.

**Comment by dangwu** [comment]
Added today! Scraped HTML.
