### ISSUE TITLE
[Feature] Folders in Favorites Section

### ISSUE THREAD

**Issue by RobertWetzler** [dangwu/Octal#292]
The "Add to Favorites" feature is one of my favorite features - though I often want to categorize the posts/comments I save there to I can easily find posts later about various topics.

It would be nice if users could create their own folders within the Favorites section.

This was a feature of Apollo for Reddit before it went extinct.

**Comment by dangwu** [comment]
Favorites uses the real HN API so it syncs with your HN account. No way to add folders to this unfortunately
