### ISSUE TITLE
Not loading categories anymore. rss/api changed?

### ISSUE THREAD

**Issue by romanr** [dangwu/Octal#297]
Other apps still work but show (null) in place of posts author names and some other fields. Looks like Octal depends on strict format.

**Comment by dangwu** [comment]
Still working over here. Octal uses the official API with SDK, so very unlikely it would just break like that.

**Comment by romanr** [comment]
I've read your comment and checked- it's working now, but slowly. one stories tab loads and when I touch on second, second stays empty for few seconds, then loads. 

looks like server related, thanks anyway!

**Comment by dangwu** [comment]
The API definitely couldve been flakey/down. Appreciate the report
regardless!
