### ISSUE TITLE
[Feature] Two column mode iPad

### ISSUE THREAD

**Issue by ArabCoders** [dangwu/Octal#30]
Hi

is it possible that you support two column mode on ipad? right now with 12.9 ipad the one column mode is huge and distracting. 

Thank you.

**Comment by dangwu** [comment]
2-column mode is in the works

**Comment by ArabCoders** [comment]
@dangwu any update about the this future?

**Comment by dangwu** [comment]
This is the next big feature I want to add. I’m just prioritizing bug fixes
(notably the rare freezing issue) for now. I also just started a new job so
it may take a bit longer than normal to get this out.

**Comment by mttjj** [comment]
Just adding my vote for this feature. Octal is my main HN client on my iPhone but I’ve stuck with MiniHack on the iPad because of the two-column support. As soon as it’s implemented in Octal, I’ll be making the switch!

**Comment by tonilampela** [comment]
Adding my vote also. Maybe introducing the column mode now with iPadOS 14 would make sense?

**Comment by dangwu** [comment]
This is coming soon!

**Comment by ArabCoders** [comment]
> This is coming soon!

Glad to see it's coming, still the best hacker news reader app. Thank you for your time.

**Comment by dangwu** [comment]
v4.0.0 is out with 2-column support on iPads!

**Comment by voiprodrigo** [comment]
Can you please enable an option to keep the original layout? I use a regular iPad aid 2 on horizontal orientation and this two column layout ruins the experience. Thank you!
