### ISSUE TITLE
App crashing on launch

### ISSUE THREAD

**Issue by trilorez** [dangwu/Octal#305]
Since yesterday afternoon, the app has suddenly started crashing on launch for me.

**Comment by dangwu** [comment]
Strange - no other reports of this and I'm not seeing it myself. Still
happening for you? Did you force-restart the app?

**Comment by trilorez** [comment]
Still happening. I tried deleting and reinstalling the app but it didn't help.

**Comment by dangwu** [comment]
What device and OS?

**Comment by trilorez** [comment]
iPhone 15 Pro, iOS 18 Beta 3. It is a beta OS but it was working fine until the middle of the day yesterday.

**Comment by trilorez** [comment]
The app appears to be working again, I'll close the issue and reopen if the behavior starts up again
