### ISSUE TITLE
Opening HN URLs to the specific post/story

### ISSUE THREAD

**Issue by gingerbeardman** [dangwu/Octal#308]
I can use Opener app to open Hacker news URLs in Octal, but they only open the app not the post.

Expected
- Open the specific post

Example
- https://news.ycombinator.com/item?id=41562849

**Comment by andelink** [comment]
Same here. When I open an `octal` link it only opens the app, not the specific post e.g. `octal://news.ycombinator.com/item?id=41562849`

**Comment by dangwu** [comment]
Thanks for the reports. Something must’ve broke after building with Xcode
18 and moving to the latest Firebase version. Will fix soon (need a few
days due to the trip I’m on)!

**Comment by dangwu** [comment]
Fixed!

**Comment by andelink** [comment]
Thanks! Can confirm it's working now 🙏

**Comment by gingerbeardman** [comment]
AWESOME
