### ISSUE TITLE
Can’t open links in comments

### ISSUE THREAD

**Issue by ekoranek12** [dangwu/Octal#31]
The tap-to-collapse support for comments makes it difficult to tap links in comments. Long pressing the link opens a contextual menu with an open option, but this opens Safari and ignores the current browser preference in Octal.

![img_0562](https://user-images.githubusercontent.com/8239273/52659711-92ecbe80-2ec3-11e9-91b9-08cc68b42010.png)

**Comment by luckman212** [comment]
If you tap *exactly* on the URL, you can still open them, but it's not always easy. I for one never use the "collapse thread" feature so I agree, it would be really nice if that setting could be toggled on/off.

**Comment by ekoranek12** [comment]
I really like the collapse feature but tapping links should definitely be able to work in tandem. I use Apollo for my reddit client and it handles this perfectly, so it must be possible!

**Comment by dangwu** [comment]
Found the bug. Fix coming soon. Also adding a setting for 'tap comment text to collapse' incase anyone doesn't like it.

**Comment by luckman212** [comment]
This is great, working excellent now.

**Comment by ekoranek12** [comment]
Oh yeah. This works beautifully!
