### ISSUE TITLE
Flagged posts displayed with blank title

### ISSUE THREAD

**Issue by Piccirello** [dangwu/Octal#316]
Flagged posts are displayed in Octal without a title, but on HN are displayed with the title "[flagged]".

Example: https://news.ycombinator.com/item?id=41732798

![IMG_4992](https://github.com/user-attachments/assets/7592d2cb-4f84-4346-8fc3-3d680a5bf5ab)
![IMG_4993](https://github.com/user-attachments/assets/11fd1a87-5bc0-434a-8902-a90f96f19cfa)

**Comment by dangwu** [comment]
Ohh nice find. Will try to fix. The API likely doesn't vend the title in this scenario, so it'll have to just say `[flagged]` as well

**Comment by dangwu** [comment]
I don't see it flagged anymore, and there's actually no way for me to detect using the HN API, so I'm going to close this for now:

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-04 at 11 32 33](https://github.com/user-attachments/assets/c9158e57-8745-40bf-8861-48fafe1be279)

**Comment by Piccirello** [comment]
I'm waiting to find another flagged post so that I can see how it's represented in the API. I suspect the post's title is blank, though it's unclear if that will always mean the post is flagged.

**Comment by Piccirello** [comment]
I reached out to dang about this scenario. It seems there are three relevant cases:

a) a post that is flagged (but _alive_)
b) a post that is dead (but _unflagged_)
c) a post that is both flagged AND dead.

In the case of a flagged post, the title comes back as normal. HN's UI prefixes this post with `[flagged]`, but that state doesn't seem possible to detect via the API.

```sh
$ curl -s "https://hacker-news.firebaseio.com/v0/item/41770249.json?print=pretty"
{
  "by" : "_1",
  "descendants" : 87,
  "id" : 41770249,
  "kids" : [ 41770516, 41770398, 41770426, 41770387, 41770370, 41770456, 41770556, 41770501, 41770443, 41770428, 41770360, 41770604, 41770517, 41772576 ],
  "score" : 110,
  "time" : 1728330853,
  "title" : "Sam Altman Goes Full Emperor",
  "type" : "story",
  "url" : "https://nonzero.substack.com/p/sam-altman-goes-full-emperor"
}
```

In the case of a dead post, the title is omitted entirely from both the HN UI and the API. The API does however include the property `dead: true`.

```sh
$ curl -s "https://hacker-news.firebaseio.com/v0/item/41770359.json?print=pretty"
{
  "by" : "daddyshortlegs",
  "dead" : true,
  "id" : 41770359,
  "score" : 1,
  "time" : 1728331445,
  "type" : "story"
}
```

Then there's the case of a flagged AND dead post. I believe (though haven't confirmed) this was the state of the post I shared in the OP. Notably, the HN UI displays the title as `[flagged]`, and the API omits the `title` property entirely. The API does however still include the property `dead: true`.

```sh
$ curl -s "https://hacker-news.firebaseio.com/v0/item/41770407.json?print=pretty"
{
  "by" : "Rayzonsql",
  "dead" : true,
  "id" : 41770407,
  "kids" : [ 41770408 ],
  "score" : 1,
  "time" : 1728331686,
  "type" : "story"
}
```

In the OP I referred to this being an issue of dealing with flagged posts, but I think that was a red herring. Even when a post is flagged, the API returns the correct title. I think this is actually an issue of dealing with dead posts.

The tricky bit here is that there doesn't seem to be a way to distinguish a dead (but alive) post from a dead AND flagged post using the API. I think a solid workaround could be to display the title as `[dead]` in either case.

**Comment by dangwu** [comment]
Wow, incredible research. Thank you! I can definitely display dead stories with [dead]
