### ISSUE TITLE
Ability to reply to story from within story

### ISSUE THREAD

**Issue by gingerbeardman** [dangwu/Octal#318]
It's currently not possible to reply to a story when you're viewing its comments. 

You can only reply to a comment, or reply to a reply. 

You can only reply to a story from the main index.

**Comment by dangwu** [comment]
When viewing its comments you just use the bottom `Add comment...` footer

**Comment by gingerbeardman** [comment]
Ah! That disappears when you scroll so I forgot it was even there.

Looks like you have to scroll back up a little bit to get it to reappear.

Thanjs
