### ISSUE TITLE
Tiny little "story numbers"

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#32]
I noticed with the last update, in "standard" view mode there are now tiny numbers indicating the story sequence # :

![image](https://user-images.githubusercontent.com/1992842/52729305-eaa02e00-2f86-11e9-83b2-f10fc409ed0a.png)

These are *really* small on my phone and with my 40+ year old eyes they are basically impossible to read unless I turn on the magnifier. Can anyone see these? I am not sure what the use of seeing the story's number is but I would like to suggest removing these...

**Comment by dangwu** [comment]
I actually added these rank numbers from a feature request here. I'll make them a bit larger :)

#10

**Comment by luckman212** [comment]
Ah I see (no pun intended). Thanks

**Comment by dangwu** [comment]
Made slightly larger with today's release
