### ISSUE TITLE
[Bug] Unlock Octal Premium not working

### ISSUE THREAD

**Issue by euihyunlee** [dangwu/Octal#323]
**Unlock Octal Premium** fails with the following error message and hangs indefinitely:

> Something went wrong. Please try again later.

I've tried reinstalling the app and rebooting the device (iPhone 12 running iOS 18.0.1).

![IMG_0007](https://github.com/user-attachments/assets/6585782a-ac17-4592-932f-28367aa7440e)

**Comment by dangwu** [comment]
Thanks! I forgot to add it back to available after fixing the app. It should work within a few minutes.
