### ISSUE TITLE
Favourites feature is not working 

### ISSUE THREAD

**Issue by feynon** [dangwu/Octal#326]
![IMG_2073](https://github.com/user-attachments/assets/e56e49ae-327c-4ba7-9be9-34fe73594ba0)
The app fails to save and fetch favourites.

**Comment by dangwu** [comment]
Thanks for letting me know. Will look into this soon. I see the fetch failing as well.

**Comment by dangwu** [comment]
The HTML format of the favorites page changed. An update with the fix to parse it is awaiting Apple review

**Comment by dangwu** [comment]
Fixed!
