### ISSUE TITLE
Bug: Compact & Minimal layout modes are identical

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#33]
I wasn't sure you'd be able to see the comment I made in #2 since that issue was closed so I am opening this here in case.

There seem to be 2 bugs with the new "minimal" view:

1. "Compact" and "Minimal" both look the same - I think that "Compact" is supposed to display the source URL, but it isn't.

2. The way the slider is laid out feels backwards to me - sliding to the left I would expect to make the view more compact (smaller) in accordance with the font size slider.

**Comment by dangwu** [comment]
Fixed both and releasing today. Silly bug - sorry about that!

**Comment by luckman212** [comment]
Perfect now, thank you
