### ISSUE TITLE
Tapping any "Ask HN" article crashes app (2.12.2)

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#35]
In the latest version, whenever I tap any "Ask HN" article, the app instantly crashes. If I instead tap the small "comment balloon" then it opens correctly. Only tapping the main area causes the crash.

**Comment by dangwu** [comment]
Whoa. Fix coming out tomorrow.

**Comment by dangwu** [comment]
Fixed with 2.12.3. You’re a lifesaver!
