### ISSUE TITLE
Small strange circle/void area when pressing on story

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#36]
This small circle is visible when tapping and holding on a story in either "compact" or "minimal" modes. Believe it is a mask of the story number left over from standard view.

**Comment by luckman212** [comment]
![8b825485-9b19-4e50-a7b9-4aab6e0b9846](https://user-images.githubusercontent.com/1992842/52922107-4bfc3000-32ec-11e9-92cb-62f07aa7b8d1.jpeg)

**Comment by dangwu** [comment]
Good eye... fix coming out tomorrow

**Comment by dangwu** [comment]
Fixed with 2.12.3
