### ISSUE TITLE
Filter widget doesn't turn orange anymore

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#37]
Small nitpick: but with update 2.12.3 the filter widget at the top no longer turns orange anymore when the filter is enabled. This was a nice visual cue that filtering was turned on; please bring it back!

**Comment by dangwu** [comment]
I knew you would notice this, haha. I was annoying at the ugliness of the orange icon. Will add a new icon that looks better very soon.

**Comment by luckman212** [comment]
Ok no problem. For me the orange icon was fine. But, if you want a suggestion, maybe switch to the more traditional "funnel" icon to indicate filtering on/off. Maybe a modified version of this (I'm on mobile now so I can't paint them but maybe an "empty" and then "filled" version of this funnel:
![](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Toicon-icon-lines-and-angles-filter.svg/240px-Toicon-icon-lines-and-angles-filter.svg.png)

**Comment by dangwu** [comment]
Added an indicator. I did try the funnel icon and didn't like the way it looked :P
