### ISSUE TITLE
Crash collapsing comment thread

### ISSUE THREAD

**Issue by ishitatsuyuki** [dangwu/Octal#38]
The app always crash when I try to collapse the topmost gigantic tree of comment of this article.

https://news.ycombinator.com/item?id=19191178

**Comment by dangwu** [comment]
Not seeing this happen anymore. I have seen something similar and I saw that we were getting malformed or missing data from the HN API.

**Comment by dangwu** [comment]
Closing for now. Feel free to reopen if it happens again
