### ISSUE TITLE
[Feature] Decrease required swipe distance to trigger actions (ex. swipe to upvote)

### ISSUE THREAD

**Issue by dbuskariol** [dangwu/Octal#39]
When you swipe left to upvote a comment but don’t swipe past halfway, the orange upvote stays with the text left aligned. 

I think if you don’t hit the halfway point it should just bounce back and hide.

**Comment by dbuskariol** [comment]
It would be great if you only had to swipe past the width of the dark orange box instead of half way too. It feels really slow to perform with a lot of swiping.

**Comment by dangwu** [comment]
There's no longer any swipe actions - closing
