### ISSUE TITLE
Please add some small navigation icons to flip between Top/Best/Ask etc.

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#4]
> Some small icons along the top or bottom of the screen to navigate between "top/best/ask/show" etc would be very convenient

**Comment by dangwu** [comment]
I like this idea, and I'm working on this right now! Planning to move to a UITabBar-based UI.

**Comment by dangwu** [comment]
Published with v.2.5.0!

**Comment by luckman212** [comment]
This is great! Thank you
