### ISSUE TITLE
Data Hog

### ISSUE THREAD

**Issue by reidcooper** [dangwu/Octal#40]
A simple start up of the app looks like it takes 2.0mb of data. Apollo reddit app does not take nearly as much. I can pay attention to the use more, but right now my gut feeling is the data usage is high.

**Comment by dangwu** [comment]
You'll have to switch the Layout Size setting to Compact or Minimal to disable thumbnails. Those are the things using a huge majority of the data. Everything else is just fetching textual data from HN.

**Comment by reidcooper** [comment]
I have minimal toggled all the way. 

Fresh start, loaded the top stories. Clicked comments of article, not article.

**Comment by dangwu** [comment]
I just tried a fresh launch, and it took 1.1 MB. Note that with a fresh launch it's fetching data for the 500 Top Stories,  plus the Ask, Show, and Jobs tabs. So I don't think ~1 MB is "data hogging". After tapping a 10 stories with 100+ comments each, it went to 2.3MB. At this point there's not much I can do, nor do I think this is unreasonable. I promise I'm not secretly uploading/downloading random data :)

**Comment by reidcooper** [comment]
I believe you, 100%. If that is what the expected data usage is then I'm fine with it. I'll probably just use it on wifi then lol. If you see any fixes that can improve it, take a look. Otherwise, great app!

**Comment by dangwu** [comment]
Thanks! I'll definitely keep an eye out and think about ways to improve.

**Comment by cedws** [comment]
Really love the app, but starting to use Octal has pushed me over my data plan. Granted that I use it a lot and I suppose a lot of the data transfer comes from browsing pages in embedded Safari, but it was unexpected for it to use this much.

Going to try turning off thumbnails.
