### ISSUE TITLE
No "Open in Safari" in share menu

### ISSUE THREAD

**Issue by ishitatsuyuki** [dangwu/Octal#42]
"Open in Safari" is a useful action that is often available in the action menu.

For some reason (maybe it's not marked as a URL?), it's not available in Octal's share actions (one triggered from comments view, and one triggered from 3D touch). The use case for this would be opening the web view of HN when some actions are not available in app.

**Comment by dangwu** [comment]
Thanks for the suggestion. I'll work on adding a "Copy HN link" options in the various Share flows

**Comment by dangwu** [comment]
Added in 3.4.0

**Comment by pcr910303** [comment]
@dangwu I’m pretty sure Open In Safari the original issuer asked is something like this: ![GitHawk Upload by pcr910303](https://i.imgur.com/q59cRGO.jpg)
Also, is this a bug? ![GitHawk Upload by pcr910303](https://i.imgur.com/jePopj0.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
