### ISSUE TITLE
3D-touching comment in thread crashes app

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#43]
See title. 3D touching a comment in thread crashes the app.
Currently iPhone XS running iOS 12.1.4. 
(I have a screen record crashing, and can reproduce it on lots of threads... but I can’t find a way to upload a video :-( )

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
Fixed with today's patch release v2.15.1. Thanks!

**Comment by pcr910303** [comment]
>Fixed with today's patch release v2.15.1. Thanks!

@dangwu Thanks for your super-fast fix! It very much enhanced my HN :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
