### ISSUE TITLE
Post text implemented as textbox has unexpected consequences

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#44]
I’m a noob in iOS app development so I’m not sure if it’s the best way to implement post text, but there are some unexpected issues with the textbox that contains the post body text.
For example, in the post [Show HN: I wrote a book about WebAssembly](https://news.ycombinator.com/item?id=19274941), holding the link appearing in the body text allows dragging the link text and move around, place it somewhere else. (I have a screen record, and it would be reproducible) I couldn’t reproduce it, but sometimes, clicking the body text also sometimes bring up the keyboard. It would be better if the body text is implemented as static text.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
Good find. I've disabled dragging in today's patch release v2.15.1. Hopefully this fixes all the issues. Thanks!

**Comment by pcr910303** [comment]
@dangwu I was happily using Octal today when I saw this: 
[Video](https://bashupload.com/feqXY/B749E921-A301-4DE6-B231-B2F3C4AC7FBF.MP4)
This bashupload link expires after 7days, please mention me if it expires!
 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
Weird! For some reason I can't select that text myself. However I believe the issue is that I need to disable textDragInteraction on that UITextView. Will fix shortly!
