### ISSUE TITLE
Links headed to `news.ycombinator.com` should open the thread in-app

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#45]
It would be good to open HN links that appear in comments in-app. There are plenty of comments that link to another thread or comment, but clicking that sends to a Safari in-app browser.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
They definitely should. I've been meaning to add this and will get around to it soon!

**Comment by dangwu** [comment]
Added in 3.1.2!
