### ISSUE TITLE
Unable to unselect text in comment

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#46]
I, as a non-native English speaker, frequently select english words and use the ‘Look Up’ feature. After looking up, I usually deselect the selected text(since the popup blocks my view) by tapping other part of the paragraph. However, unselecting by tapping on an ‘Octal comment’ after selecting a portion of text doesn’t work. I’m not sure if it’s intended behavior (Maybe for the 3D touching on comments?), but I find this particularly irritating(I currently deselect by folding and unfolding a comment). Can this be fixed?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
Will look into this

**Comment by dangwu** [comment]
Have you tried turning off 'Quick Collapse' for comments in the Settings?

**Comment by pcr910303** [comment]
@dangwu I already have tried this, but it was no  use. Tried again, but doesn’t work.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
Got a fix coming. Should be out tonight or tomorrow!

**Comment by pcr910303** [comment]
Fix works! Thanks!!
