### ISSUE TITLE
View freezing 2.16.1

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#47]
I can't figure out exactly how to reproduce it yet, but with this latest version I am getting a lot of freezing.

When leaving and re-entering the app, the main view will freeze and become completely unresponsive to any taps for approximately 30-60 seconds. If I wait long enough, it eventually unfreezes and I can scroll through the stories again (or if I'm impatient, I force quit the app and re-enter)

I will add more detail if possible but wanted to mention it. Thank you for the continued updates!

**Comment by dangwu** [comment]
Yup I noticed this in 2.16.0 as well, a few days ago but it seemed to have
stopped. Let me know if you find consistent repro steps!

**Comment by luckman212** [comment]
I am trying to find a good repro. It's still happening for me on 2.16.1 as of today. Is it related to internet connectivity?

also, #27 has returned!

**Comment by dangwu** [comment]
I just hit publish on 2.16.2 that hopefully fixes this.

**Comment by luckman212** [comment]
Might be too soon to tell, but so far since updating to 2.16.2 I have not seen the problem come back! Fingers crossed...

**Comment by dangwu** [comment]
I can say with 99.99% certainty that this is resolved now with today's 2.17.0 release! Fixed a memory leak that would definitely cause slowdown the longer the app stayed open and used.
