### ISSUE TITLE
Mark story as read after clicking on a story

### ISSUE THREAD

**Issue by andrenasri** [dangwu/Octal#48]
Feature Request:
It would be very helpful if stories were automatically “marked as read / visited” after clicking on the story.

Thank you for all of your great work on Octal!

**Comment by dangwu** [comment]
Clicking on the story or clicking on the comments?

**Comment by andrenasri** [comment]
Clicking on the story.

**Comment by dangwu** [comment]
Added with today's 3.2.0 release. Appreciate the suggestion!

**Comment by andrenasri** [comment]
Thank you @dangwu - greatly appreciate your work on Octal 🎉
