### ISSUE TITLE
[Feature] Long press on URLs in comments to bring up share-sheet

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#5]
Long-pressing on a URL in comments doesn't do anything. It brings up a bubble around the URL and you can "drag" that around, but you can't drop it anywhere. Is this a bug?

I would like to long-press URL from comments and have it bring up the share-sheet (this is what MiniHack does, and that is very convenient for saving interesting links that you come across in the comments)

**Comment by luckman212** [comment]
It's a bit of a crazy game to try to press it "just right" ... not too hard (oops it opened in Safari) or too soft (oops now I'm dragging around a bubble that I can't do anything with). 

I figured out the way to do it: you have to press _just barely_ and without moving your thumb at all - not even 1 pixel. If you can manage this, and get the bubble to appear, and then not drag the bubble anywhere and release your thumb, then a panel will appear with the "Share" option.

Not sure if it's possible to override this built in functionality of UITextView but it would be much better if the long press or 3D touch simply went straight to the share sheet.

**Comment by luckman212** [comment]
Seems like with recent versions of Octal, there is no more long-press-on-link action to trigger the share sheet. As soon as a link is clicked or long-pressed, it immediately opens the browser. This feels like a regression.

**Comment by dangwu** [comment]
Fix coming. ETA 24 hours

**Comment by dangwu** [comment]
Added in 3.16.0
