### ISSUE TITLE
Squashed navbar

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#50]
The other isssue (#27) was closed, so I'm posting separately. I don't know why this keeps happening to me, I guess I'm lucky? But this is with today's 2.17.0 version...

![2256C41A-40A5-44C0-9281-642EA60CA676](https://user-images.githubusercontent.com/1992842/54469664-6e5d5e00-4771-11e9-843b-085c0de52f1b.png)

**Comment by luckman212** [comment]
Before I force close the app, is there any way to collect any useful information on how it gets into this state?

**Comment by dangwu** [comment]
I encountered this once recently and some preliminary google searching [1] leads me to believe this is just an annoying UIKit bug. Are you using an iPhone X? 

[1] https://stackoverflow.com/questions/47054707/how-to-correct-tab-bar-height-issue-on-iphone-x

Note that the fix there is to use safe area layout guides, which I already use.

**Comment by luckman212** [comment]
Hmm, yes I do have an iPhoneXS. I read that thread and it looks like there are posts more recent than the Accepted Answer, from the end of 2018 with users reporting they've solved it.

One guy says to "[align the bottom of the UITabBar to the Superview][0]"

Another says "[solved this issue by overriding safeAreaInsets in the UITabBar subclass][1]".

And one guy towards the bottom of the page says "[had a a similar issue. I was setting the selectionIndicatorImage in viewDidLoad(). Moving the code to viewDidLayoutSubviews() fixed my issue][2]"

I'm not smart enough to know if any of that could help here but, it seems like maybe it could.

[0]: https://stackoverflow.com/questions/47054707/how-to-correct-tab-bar-height-issue-on-iphone-x/51716637#51716637
[1]: https://stackoverflow.com/questions/47054707/how-to-correct-tab-bar-height-issue-on-iphone-x/53170130#53170130
[2]: https://stackoverflow.com/questions/47054707/how-to-correct-tab-bar-height-issue-on-iphone-x/50091912#50091912

**Comment by dangwu** [comment]
None of those apply to Octal since I use a vanilla UITabBarController and don't use a standalone UITabBar or subclass. However, I've applied a 'override sizeThatFits and account for safe area' fix from SO and will release tomorrow. Fingers crossed!

**Comment by luckman212** [comment]
Is that in 2.17.1?

**Comment by dangwu** [comment]
Yes it is. Has it helped?

**Comment by luckman212** [comment]
Too soon to tell :hourglass:
But I will definitely report back soon!

**Comment by dangwu** [comment]
How's it looking? :)

**Comment by luckman212** [comment]
I think everything's fine now; it hasn't happened again. Let's declare victory!  🥇

**Comment by dangwu** [comment]
Hooray!
