### ISSUE TITLE
Search with no results doesn't indicate of no results

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#52]
Try searching random words (eg. `Abc def sksk`), scroll down, and then scroll up!
It looks like it's keep searching...
I'm not sure, but (if my memories are correct) a search that only yields a few(2 or 3) articles also show something similar in the background.

**Comment by dangwu** [comment]
Good find! WIll definitely fix this.

**Comment by dangwu** [comment]
Fixed!
