### ISSUE TITLE
Comment link opening inconsistencies

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#53]
I set the browser as Safari In-app.
When I click the link lightly, it opens in Safari In-app, while when I click the link slightly longer (but not enough to show up the context menu) it opens in Safari. 
Below is a video that shows it. The first three light taps open in Safari in-app while the last three taps open in Safari.
[Video](https://bashupload.com/bEHGZ/6394F1A8-6287-473B-BD37-F590FD66FBE7.MP4)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
Good find. Looking into this

**Comment by dangwu** [comment]
Fixed today
