### ISSUE TITLE
Loading animation glitches

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#54]
Okay, so I'm not sure if this is perfectly reproducible, but I've seen many reloading animation glitches (even before it was updated: BTW, the new animation is super pretty! :-) )

For me, it was reproducible with the following steps:
1. Go into any article comments
2. Tap any link (to go to Safari in-app)
3. Come back
4. Reload (with animation)
5. Tap a link again.
6. Come back
7. Reload (with animation)'
8. Tap a link again.
9. Come back
10. Reload -> No more reload animation

I'm not sure if it's always reproducible with these steps, and it's surely not the only way as I could also find reloading animation glitches from coming out of app.

[Video_1](
https://bashupload.com/SZ5FC/B7A808C1-4B88-4C17-97E3-6F19AC065438.MP4)
[Video_2](
https://bashupload.com/_PmIf/76E981F2-217D-47CC-A155-CC3545054AC1.MP4)

**Comment by dangwu** [comment]
Yeah I've seen it disappear before too. Will do my best to resolve.

**Comment by dangwu** [comment]
Has this happened to you since updating to 2.17.1?

**Comment by luckman212** [comment]
So far it hasn't! 🤞  I am hopeful.

**Comment by pcr910303** [comment]
@dangwu Me too! Using 2.17.1 for a whole day and have not seen any glitches :-)
BTW, after the animation, the bounce feels a little wierd... slowing down would feel more natural IMHO.
Thanks for making this great app!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
@pcr910303 the bounce? do you just meant he 2 circles move too quickly?

Also thanks everyone for the data!

**Comment by pcr910303** [comment]
@dangwu I was meaning that the refreshed page itself goes up too quickly (after the loading is finished and the comments are refreshed).

**Comment by dangwu** [comment]
Ah, I see. I'll try to slow it down slightly for the next release.
