### ISSUE TITLE
Dark keyboard in dark themes

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#55]
As a person who uses dark mode for my battery life (I’m using iPhone XS with an OLED screen), I would appreciate if the keyboard when searching will also be black, just like the iOS Messenger Dark mode. (Like in the picture)
![Dark keyboard in Messenger](https://i.imgur.com/Dwry6ol.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
Fixed in 2.17.3! Thanks!
