### ISSUE TITLE
Remove highlight from the author name

### ISSUE THREAD

**Issue by ishitatsuyuki** [dangwu/Octal#56]
The orange accent on the author has been most times attracting unneeded attention. There isn't much point on just the name of someone you don't know, and I think removing that accent makes the compact view look better.

**Comment by dangwu** [comment]
I think the active HN community is actually quite small and you start to recognize authors the more you read/participate. However, design-wise, I do agree that the author name is currently a little too bold. I'm playing with reducing the weight of the author names for now.

**Comment by dangwu** [comment]
I've reduced the boldness slightly. Will keep this feedback in mind for the future if I ever do a major UI re-design. Thanks!
