### ISSUE TITLE
[Feature Request] Animation in reloading articles

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#58]
Related: #54

I have thought a while why the reloading animation in a single comment thread looks awkward even when there are no glitches (BTW, the glitches decreased but didn’t disappear:-( ).
Then I saw the main screen reloading and found out that the animation (the orange thing that displays when I pull the thread to reload) should only be displayed when I am pulling the thread and the thread should be in a loading state(something like when I first go into the thread) instead displaying the outdated thread pulled down. (Something like the main thread.)
I’m having a bad time expressing my thoughts (as I’m not a native English speaker), but I hope you understand:-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
I'm 99% sure I understand what you mean. Will be updated in the next release (ETA tomorrow).

**Comment by pcr910303** [comment]
@dnagwu That’s great! I’m sure you’re one of tbe best app devs that gives great feedback 😍 ...
Seriously, do you have any intent to make an HN macOS app(with a small price)? I’m usually skeptical in buying apps, but I think an app you make will be great :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
Haha, thanks! I have no plans to make a macOS version. I want to add iPad 2-pane support first, and before that I want the iPhone version to be the best it can be.

**Comment by dangwu** [comment]
Feel free to reopen this if you still see an issue with the latest update (v2.19.0)

**Comment by pcr910303** [comment]
Thanks, that’s great 😍 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
