### ISSUE TITLE
[Bug] Comment thread from search screen

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#59]
When I click a comment thread from search screen and (go little down and) go back, the comment numbers look big: please check the picture.

![Big comment number from comment thread to search screen](https://i.imgur.com/tnK78HD.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
Can you see if this is still an issue with the latest update? (v2.19.0)

**Comment by pcr910303** [comment]
Yup... 😞 It looks like the topbar text is changed from comment numbers to the post title: the issue persists...
![](https://i.imgur.com/5fLXID3.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
I've reproduced this and I'm fairly confident that it's a UIKit bug related to prefersLargeTitles and UISearchControllers. Probably won't try to fix it since it would be some hacky fix and this isn't that important.

**Comment by pcr910303** [comment]
@dangwu Looks like this is fixed! Was there any changes from Octal’s side, or is the iOS bug fixed?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
