### ISSUE TITLE
Share button - more taps

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#60]
The new feature that lets you choose whether to share the comment or the story link to the share sheet is definitely useful (for some).

Personally, I rarely want to share the link to the story- so this is just an extra tap with room for error each time.

I suggest a toggle in settings that turns this off and reverts to the "old" way (share from comment screen=comment link, share from story page/internal browser=story link)

Sorry to nitpick.

**Comment by luckman212** [comment]
Also, to add to this: there is no purpose of having this choice in the "Ask HN" section, since there are no story links there.

(Clicking "Story link" in that case does nothing)

**Comment by dangwu** [comment]
I'll keep this suggestion in mind but for now I don't plan on adding a new setting for this. Doesn't seem like that big of a deal, and don't want to pollute settings with a lot of little things that most people don't care about. Good find for the 'Ask HN' issue though - will fix that.

**Comment by luckman212** [comment]
I agree about cluttering the settings with too many trivial things, however I disagree about the original change to add this extra popup menu.

What was wrong with the old way where, if you want to share the story link, just tap on the story and then tap share? If I'm reading the comments and tap share, 99% of the time I intend to share the link to the comments- so again this choice is just extra taps.

**Comment by luckman212** [comment]
What is the point of a popup menu with only 1 choice?

![image](https://user-images.githubusercontent.com/1992842/56458876-f67ae880-6359-11e9-8c98-1079b3e741b8.png)

**Comment by dangwu** [comment]
Haha, I knew you'd point this out :P Fixing soon.

**Comment by dangwu** [comment]
Fixed in 3.1.2!
