### ISSUE TITLE
Load less articles at once

### ISSUE THREAD

**Issue by ishitatsuyuki** [dangwu/Octal#61]
I'm on a limited mobile data plan - and with that connection refreshing is pretty slow.

I don't think we need to load 100+ articles at once; can you load like 50 initially then more on demand?

**Comment by dangwu** [comment]
Sorry - not going to do this because HN is actually migrating to a new JSON-based API soon which will render this work useless. Also, I don't think loading 50 instead of 100 would actually improve real-world speeds. The articles themselves are a very small amount of data (title + url + counts).

**Comment by ishitatsuyuki** [comment]
In #40 you said it's 500 stories (and 1MB) - that's a lot (even a web page doesn't always goes up to 1MB). There's a room of improvement.

The recently launched Hacker Feed app works pretty much faster, as it lazily loads as you scroll/switch tabs.

What's that "new JSON-based API"? Is that different from Firebase? From the API perspective in general, I wouldn't expect such big size of pagination since querying database is a steady cost.

I hope you would implement lazy loading.
