### ISSUE TITLE
[v3.1.0] Jump to next comment button can be moved to unreachable area

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#62]
Being able to drag the "jump to next comment" button presents 2 new problems:

1) If you drag it too low on the screen of an iPhoneX, it becomes impossible to drag it back "up" because any tap and hold in the bottom region triggers the "app switcher" mode.

2) if you drag it to "high" (into the "Title" area) it will go "underneath" the Title and basically disappear forever. This is what I did yesterday, and I've not found any way to bring that button back. 😢

**Comment by dangwu** [comment]
Ugh, good finds. For #2, there is code that automatically resets the position if you drag it behind the navigation bar, and I'm surprised it isn't working for you. #1 is real though and I've reproduced it. I'll likely have to add a reset button in settings.

**Comment by luckman212** [comment]
Just to step back a bit, what is the real use case for being able to move that button around? For me I've never thought that I'd like to move it. Did someone request this feature?

**Comment by dangwu** [comment]
Yup, someone said they liked how reddit's moved, and it's useful for
positioning exactly where the person's thumb naturally lands. Especially if
they're left-handed or on a tablet.

**Comment by luckman212** [comment]
Wow, I never even knew that Reddit's was movable (until now). I just played with it for a bit. It does seem like they've solved the issue by having the button "snap" back when it's dragged into the danger zones (very top or very bottom).

**Comment by dangwu** [comment]
Haha yup. I added the 'snap back' today with 3.1.1. Hopefully it fixes it
for you. If yours is already lost then you may need to delete and reinstall
the app

**Comment by luckman212** [comment]
Thanks. Had to uninstall & reinstall to get the button back, but now the snapback does seem to work 😁

Due to the re-install, I encountered a strange bug though: #65
