### ISSUE TITLE
[v3.1.0] Flickering comments while loading

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#63]
Seems to be a new bug: stories with a lot of comments (>300) cause a lot of flickering for the first few seconds while loading. This did not happen before.

Here's a comment link from yesterday that definitely triggers this every time for me:
https://news.ycombinator.com/item?id=19674218

And here's an animation showing it in action:
![sample 2019-04-17 13_31_39](https://user-images.githubusercontent.com/1992842/56308452-59c80900-6115-11e9-90e1-2011b4e6a0d7.gif)

**Comment by dangwu** [comment]
I'm fairly sure this was an existing issue as I've seen it before for huge comments. Will get around to diving into it eventually

**Comment by dangwu** [comment]
Resolving because I haven't seen it in a while
