### ISSUE TITLE
Preventing swiping to upvote a comment if it's already been upvoted

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#64]
Can't be 100% sure of this but at least for me, upvoting is broken in 3.1.0

Trying to upvote stories from the main view, or comments from the comment view, provides no feedback.

No error message is shown, nor any confirmation that the upvote was submitted. (There used to be a small toast popup).

**Comment by dangwu** [comment]
Heya - I actually removed the toast for upvoting. It was a bit overkill as the icon turns orange when tapping. If the upvote actually fails there is an alert popup and icon goes back to gray.

**Comment by luckman212** [comment]
I don't see any color change etc. For me the up arrow is always orange. Before, during and after the upvote.

I noticed on the main story list, the upvote option disappears after you have upvoted. However, on the comments page, you can keep swiping and tapping upvote over and over.

**Comment by dangwu** [comment]
I just realized that you're talking about he swipe action and not the actual up arrow on the cell. You're right, the comments should be smart and prevent the swipe action if you've already upvoted something! Will fix that soon.

**Comment by luckman212** [comment]
Thanks, yes that's correct

**Comment by dangwu** [comment]
Fixed!
