### ISSUE TITLE
[Bug] Crash when using Bitwarden + iOS Autofill password feature

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#65]
I use [Bitwarden](https://bitwarden.com/) to store & sync my passwords across devices.

After uninstalling / reinstalling Octal to try to fix bug #62, I encountered this strange issue:

When trying to log in to my HN account, I tap the "Passwords" button to trigger the Bitwarden autofill, and it appears - just briefly - and then exits (crashes?) after about 1.5 seconds. I tested this multiple times to confirm it. It doesn't happen with any other apps or sites that I have encountered. Certainly a bit strange, but I filed [#487](https://github.com/bitwarden/mobile/issues/487) over there as well to see if the bug is on their end.

Here's a video clip:

![RPReplay_Final1555651082-s 2019-04-20 09_07_20](https://user-images.githubusercontent.com/1992842/56457661-1b685f00-634c-11e9-9b97-88498f2ecc4f.gif)

**Comment by dangwu** [comment]
I haven't used password apps at all, but it looks like from your video that it's Bitwarden that is crashing and not Octal?

**Comment by luckman212** [comment]
Correct - but the question is why only from Octal? I was hoping you might have some idea, since this is the only case where it happens. Calling Bitwarden from dozens of other sites/apps works so there must be something unique going on here. I opened the issue on Bitwarden's end as well but the dev responded that he can't see a reason for the crash.

**Comment by dangwu** [comment]
I'm not doing anything crazy. Normal UIKit UITextFields and stuff.
Hopefully they can find a crash report/stack trace on their side.

**Comment by luckman212** [comment]
Just an update for people not following the other issue: Bitwarden says they are rebuilding their iOS app, so hopefully the bug really is on their side and will be fixed after the overhaul.

**Comment by luckman212** [comment]
Update: sorry to report but the rewritten Bitwarden iOS app is out, and amazingly still crashes in the exact same way when called from the Octal login page.

I will post again to their https://github.com/bitwarden/mobile/issues/487 issue as well...

**Comment by luckman212** [comment]
Bitwarden iOS app ver 2.2.1 (released 8/19) seems to fix this crash at last.
