### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by neuhaus** [dangwu/Octal#67]
Editing a post that contains at least one apostrophe will lead to an encoding where the apostrophe characters get (double) encoded as &#x27;

**Comment by neuhaus** [comment]
Sorry they get encoded as & # x27; (remove the spaces)

**Comment by dangwu** [comment]
I'm not seeing this. Can you provide example text?

I tried: ```This is a test comment with apostrophe's```

And then when I edit, it correctly displays with the single apostrophe.

**Comment by dangwu** [comment]
Should be fixed with today's release, v3.2.2. Let me know if you still run into problems.
