### ISSUE TITLE
Enhanced indication for filtered lists (min pts/comments)

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#68]
_Suggestion:_

The small pencil added to the "sliders" icon in the top left corner is very subtle and doesn't always catch the eye.
![IMG_9604](https://user-images.githubusercontent.com/1992842/56872116-4fe6b580-69f3-11e9-81f7-18164400f0e4.PNG)

It would be helpful if, when filtering is enabled, a small indicator such as this was added to the header to show the filter values. This would make it easier to tell when and how filters are applied.
![IMG_9604a](https://user-images.githubusercontent.com/1992842/56872117-4fe6b580-69f3-11e9-9151-a06daeb21121.PNG)

**Comment by dangwu** [comment]
Interesting idea, but kind of against iOS design guidelines, as that area should be reserved for buttons. I'll play with new "filters-enabled" icons and see if I can find one that looks good and stands out more. Or I could go back to making the icon the colored when selected.

**Comment by luckman212** [comment]
I didn't know that was against HID guidelines.

Seems like even Apple themselves are ignoring this then? E.g. their own Mail.app displays similar indications in that same area:
![image](https://user-images.githubusercontent.com/1992842/57023708-bc82cf80-6c00-11e9-9c7f-add00b45cf70.png)

(Also, it technically should be a button, since if tapped on I would expect it to open the filter popup to allow the values to be changed, so maybe this doesn't conflict with the guidelines after all?)

**Comment by dangwu** [comment]
I'm going to try overlaying a badge with # of filters active on top of the existing button (just like the blue '1' in your screenshot above). I don't like the idea of having 3 separating buttons that all do the same thing

**Comment by luckman212** [comment]
Ok that sounds good. I was not trying to clutter or make the interface too crowded. The badge is a good idea.

My only suggestion for that is: maybe it's more useful for the badge to just show instead larger of the 2 filter numbers? E.g if min comments is 5 and min points is 15, the badge would display "15".

Up to you of course!

**Comment by dangwu** [comment]
That's an interesting idea. I was actually thinking that the badge would
just be 1 to 3, according to number of filters active (comments, points,
sort)

**Comment by luckman212** [comment]
If it were up to me, I would not display any special indicator/badge for sort order.

Showing a numeric value instead of just "1" or "2" seems like it conveys more information in the same amount of space, so I think it's a little more efficient. Might save you a trip to the popup box if all you wanted to do was check to see how restrictive your filtering was.

**Comment by dangwu** [comment]
Sounds good to me. Thanks for the suggestions!

**Comment by dangwu** [comment]
Badges are out! A slightly refreshed filters UI is coming soon too.

**Comment by luckman212** [comment]
I saw–thank you! I was going to post though: 
 In dark mode, the contrast is too low -  it's _very_ hard to read the number.

![image](https://user-images.githubusercontent.com/1992842/57506591-3e8e8a80-72ca-11e9-8edc-d790a556ca66.png)

**Comment by luckman212** [comment]
Looks much better in 3.4 👍 
Still wish the number in the bubble showed the number set in the filter instead of just "1" or "2" but I understand if you don't want to do that.
