### ISSUE TITLE
App crashes when resuming reader view

### ISSUE THREAD

**Issue by teddy-error** [dangwu/Octal#69]
I have noted a crash when resuming the app (via task switch). This occurs when the current view of the app is on some webkit reader, as far as I can tell.

Sorry my terminology is approximate at best; I am not familiar with iOS development.

**Comment by dangwu** [comment]
Can you share a video of this? Trying to reproduce but haven't yet.

**Comment by dangwu** [comment]
Resolving since no repro and I haven't encountered it. Will keep an eye out for this.
