### ISSUE TITLE
[Bug report] Freeze on viewing profile activity page

### ISSUE THREAD

**Issue by pcr910303** [dangwu/Octal#70]
Octal freezes on loading when viewing my profile's activity page by touching 'My profile' button on top right. 
Please see uploaded GIF.
![RPReplay_Final1557122401](https://user-images.githubusercontent.com/37990858/57208932-48d22f80-7011-11e9-9984-fd66811d13bd.gif)

**Comment by pcr910303** [comment]
The glitch in the gif is not the bug :-(
The bug is that the the page freezes while loading.

**Comment by dangwu** [comment]
Yup, I noticed this freezing starting today too, but it seems to have
stopped. Not sure if there was temporarily corrupted data or a glitch in
Firebase or something. Will keep an eye out.

**Comment by pcr910303** [comment]
@dangwu I’m pretty sure this happened since when I first made my account/logged in with Octal (about a month ago) :-( 
I was too lazy to report the bug...

**Comment by dangwu** [comment]
Weird - can you give me your Hacker News alias? I'll try to reproduce

**Comment by dangwu** [comment]
I just tried the user 'pcr910303' on HN and it loaded fine for me

**Comment by pcr910303** [comment]
@dangwu For what I tell, it’s fine seeing others/myself from other pages (like touching my account from my comment) :-( It’s the my profile page that’s freezing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
The two pages are the same. Your profile is just hard-coded to your
username.

**Comment by pcr910303** [comment]
@dangwu Well, maybe I was lucky until now. I see random freezing on any of my account page. Maybe, maaaybe it’s related on longer API access speeds?̊̈ The HN server would be far from here than the US; if you experienced similar things when the HN API fails, maybe it’s because of longer response times?̊̈

**Comment by aaykut** [comment]
I have exactly the same issue.

**Comment by dangwu** [comment]
I’m working on redoing this screen. Stay tuned!

**Comment by dangwu** [comment]
@aaykut @pcr910303  can you both try again with today's release? (v3.3.1)

**Comment by aaykut** [comment]
@dangwu - latest update works! Thanks for that.

**Comment by dangwu** [comment]
Awesome, thanks!

@pcr910303 please re-open this issue if any issue persists.
