### ISSUE TITLE
[Feature] Add a custom URL scheme

### ISSUE THREAD

**Issue by SuperTachyon** [dangwu/Octal#72]
Does Octal has a URL scheme? If not, can we have one to open HN links in the app?

**Comment by dangwu** [comment]
No plans at the moment. The only way to do that would be to use something like Opener (which someone else asked for), since I don't own the domain ycombinator.com. Is that what you were thinking?

**Comment by SuperTachyon** [comment]
No need for Opener. I can simply change “https” to the specified url scheme in the address bar in Safari. A lot of third-party apps for Reddit and Tweeter have these.

If there is a url scheme like “octal://news.ycombinator.com/item?id=18397006” to open this submission in Octal. The primary use should be for Shortcuts and other automation apps.

**Comment by dangwu** [comment]
I see! I'll see about adding a custom Octal scheme.

**Comment by SuperTachyon** [comment]
Thanks!

**Comment by timonus** [comment]
Hey there, I’m the developer of Opener and I would really love to see this added! [Hack](https://apps.apple.com/us/app/hack-for-hacker-news-coding-yc/id1464477788) recently added support for this and now Opener can open HN links in it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
Hi @timonus, I'm down to add support. What do I need to do exactly? I'm assuming I mostly just need to add a custom URL scheme?

**Comment by timonus** [comment]
@dangwu yep, you need to add a scheme and handling for different HN entities.

I would suggest the following

- For links like `https://news.ycombinator.com/item?id=10781731`, allow them to be opened using `octal://item?id=10781731`
- For links like `https://news.ycombinator.com/user?id=_jomo`, allow them to be opened using `octal://user?id=_jomo`
- For links like `https://news.ycombinator.com/from?site=matrix.org`, allow them to be opened using `octal://site?id=matrix.org`.
- For links like `https://news.ycombinator.com/front?day=2018-05-10`, allow them to be opened using `octal://date?id=2018-05-10`

**Comment by dangwu** [comment]
@timonus I've added support for those first 2 suggestions so far. What needs to be done on Opener's side? Should I publish to the App Store first?

**Comment by timonus** [comment]
I’ll handle updating thing on Opener’s side once you’ve published to the App Store :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
@timonus Woot! Thanks man. It's out now in Octal v3.7.0!

**Comment by timonus** [comment]
Rad, Opener now supports it :) 
https://twitter.com/OpenerApp/status/1142872849599754241

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dangwu** [comment]
Awesome! Thanks again! I’ll have to buy your app and check it out myself.

**Comment by quinncomendant** [comment]
I had to dig for a long while to find Octal’s URL scheme. @dangwu, would you mind updating the README.md with the ones that are supported?
