### ISSUE TITLE
[Feature Request] Swipe right anywhere on comments screen to return to main/root view.

### ISSUE THREAD

**Issue by rupino** [dangwu/Octal#74]
A lot of reddit apps have this feature, and it is a lot easier than swiping right from left screen edge, especially on larger phones. Also swipe right gesture doesn’t seem to be used for anything else currently.

**Comment by dangwu** [comment]
Good idea. Will look into this

**Comment by dangwu** [comment]
Added with today's release (3.4.0)!

**Comment by rupino** [comment]
Thanks for the super fast addition!
