### ISSUE TITLE
[Feature] Add option to disable new swipe back gesture

### ISSUE THREAD

**Issue by SuperTachyon** [dangwu/Octal#77]
It’s great to see the app is evolving fast. It would be better to have choice to disable the new features like the filter badge and “swipe anywhere” gesture.

**Comment by dangwu** [comment]
In a perfect world, everything would be optional but that would simply result in too many test cases and slow development to a halt due to all the possible combinations of features on/off. 

Is there something you not like about the fitler badg eor swipe back anywhere gesture?

**Comment by SuperTachyon** [comment]
I agree that would make settings clustered eventually. My preferences are totally personal. 

I don’t like any kind of badges in general. Because usually badges mean there are something requiring my attention and actions. But I don’t think there is a need for attention in this case. In other words, they make me a bit anxious. As for swipe back gestures, I simply don’t like this inconsistency with system gestures. 

It’s impossible to cater everybody. But more customisations would be still be a plus in my book.

**Comment by dangwu** [comment]
I can see the anxiousness of the badging. Let me think of possible new designs for that.

For the swipe back, can't you just ignore it? The normal swipe to go back still works.

**Comment by SuperTachyon** [comment]
Thanks for your understanding. You definitely have a point. But I would have already ignored all of this if it’s nothing for me. Perhaps (most likely) I am the problem here. 

Objectively, having the option to disable “full width swipe right” leaves the possibility to add swipe right actions on submissions/comments and etc.

**Comment by SuperTachyon** [comment]
[As a general rule, use standard gestures.](https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/gestures)

**Comment by dangwu** [comment]
Right, but the standard gestures are still there. A new option has been provided to do the same thing. Instagram has the same thing. Just pretend I didn’t tell you about the new gesture 😅

**Comment by SuperTachyon** [comment]
Fine. Instagram is not an example of a good app nor built-in app. If you don’t think a toggle is something reasonable to add, you don’t have to add. 

Just don’t tell me to “pretend” it’s something when it’s clearly not. Would you pretend you never heard about this gesture suggestion and remove it?

**Comment by SuperTachyon** [comment]
This feature request isn’t going anywhere. Let’s pretend all the features have been added and close this.

**Comment by dangwu** [comment]
I still don’t understand how the gesture ya bothering you. You don’t have
to use it. Are you accidentally triggering it?

**Comment by SuperTachyon** [comment]
Nope. I simply don’t like non-standard gestures. Their existence bothers me. There is nothing more than that.

**Comment by dangwu** [comment]
Let’s leave this issue open for a bit so others can see it and reply if
they share your concern.
