### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#8]
I don't know if the official HN Firebase API has a search method available, but a "search" section would be very useful.

If the API doesn't support this, maybe [hn.algolia.com](https://hn.algolia.com/?query=firebase&sort=byPopularity&prefix&page=0&dateRange=all&type=story) can be scraped (yuck)

**Comment by dangwu** [comment]
Added in v2.8.0

**Comment by luckman212** [comment]
Hey thank you so much for all the great work!

**Comment by luckman212** [comment]
I updated to 2.8 this morning and tried this out - amazing feature, very nicely done! The only change I would like to see is, a toggle in Settings to switch the default sort order from "relevance" to "date".

**Comment by dangwu** [comment]
Thank you both! I'm adding the sort order option as we speak!
