### ISSUE TITLE
[BUG] Swipe to upvote comment not working

### ISSUE THREAD

**Issue by darsnack** [dangwu/Octal#80]
Since the latest update that enables full-screen swipe back, swiping to upvote a comment no longer works. (at least not reliably to the point of never working).

**Comment by dangwu** [comment]
Yup I'm aware of this. Fix release 3.5.1 is awaiting Apple review! Thanks

**Comment by dangwu** [comment]
With 3.5.0, there is no more swipe-to-upvote, since there's a dedicated upvote button on each comment. Swipe to reply and collapse should be working normally.

**Comment by darsnack** [comment]
Closing because this is fixed in 3.5.1 awaiting Apple review.

**Comment by dangwu** [comment]
Are you having swipe-comment issues on 3.5.0?

**Comment by darsnack** [comment]
No 3.5.0 fixed it. Just saw the update.

**Comment by dangwu** [comment]
Perfect!

**Comment by darsnack** [comment]
Maybe you should consider moving the comment upvote button? It can be harder to reach left-handed on an iPhone X.
