### ISSUE TITLE
Sort by date - not sorting correctly?

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#81]
This seems like a bug to me, but not sure.

I selected **Sort By: Date** in Settings:

![image](https://user-images.githubusercontent.com/1992842/58103605-40e9c200-7bb1-11e9-8955-b2a496b632d8.png)

But in all views, the sort order does not seem to be accurate. All views affected (Top, Show, Ask...) Some examples:

![image](https://user-images.githubusercontent.com/1992842/58103694-6b3b7f80-7bb1-11e9-8744-0881b723fc08.png)

![image](https://user-images.githubusercontent.com/1992842/58103699-6d9dd980-7bb1-11e9-92f8-e336de30d3c7.png)

App ver: **3.5.1**

**Comment by dangwu** [comment]
That setting is for sorting Search results. To sort normal stories by date
you can Filter by New

**Comment by luckman212** [comment]
So there is no way to view e.g. Show HN in reverse date order?

**Comment by dangwu** [comment]
I could manually sort whatever stories the API gives me by date, but that’s
fairly arbitrary, since it only vends stories that are a few days old at
most. Since there’s only around 30 “Show HN” stories, you could just swipe
to the bottom.

**Comment by luckman212** [comment]
Ok, no problem. So you basically display the results in whatever order the API returns them? 

I was mainly just wondering. No need to change this really, you're right generally they are pretty well ordered.

**Comment by dangwu** [comment]
Yup. It’s the same order as the website. Some proprietary algorithm based
on date and upvotes.
