### ISSUE TITLE
[Feature] Add to / show favorites

### ISSUE THREAD

**Issue by Daxx909** [dangwu/Octal#82]
The Account page has a lot of empty space. Is it possible to link to favorites (and maybe upvoted posts too)?

And of course adding posts to favorites would be nice too.

**Comment by dangwu** [comment]
Good idea. Will add favorites when I get time!

**Comment by dangwu** [comment]
Added in 3.6.0, out today!

**Comment by Daxx909** [comment]
I can see favorites of other accounts now. What about my ook n favorites? (Button top right)

**Comment by dangwu** [comment]
You should be able to access your own from your profile page (sign in then
access from settings or top right avatar icon).

**Comment by Daxx909** [comment]
Nope, that page is empty (except profile name and back/signout buttons).
I'm using version 3.6.0 on iOS 12.3.1 (iPhone).

**Comment by dangwu** [comment]
So you don’t see your activity either? What’s your user name?

**Comment by dangwu** [comment]
You should also see your karma and account age.

**Comment by dangwu** [comment]
Ah, found it. Assuming you are "daxx909" - the Hacker News API returns null for you. I'm not sure why. I'll reach out to the API owner and see what's up. Maybe try posting a comment/submission and upvote some stuff to populate and try again for now.

You:
https://hacker-news.firebaseio.com/v0/user/daxx909.json?print=pretty

A normal account: 
https://hacker-news.firebaseio.com/v0/user/dangwu.json?print=pretty

**Comment by garyking** [comment]
I've got the same problem. I have zero posts and comments on HN, but I have several favorites. I assume if I post or comment, then it would populate my data in the API, but I don't want to be forced to post or comment just for that. 

Please keep us updated on what the API owner says about this, and if they're able to resolve this.

**Comment by dangwu** [comment]
Daxx, you should be fixed now. Garyking, if you send me your HN username I can forward it to HN API admin to fix. They said otherwise you need to post or comment to work.

**Comment by garyking** [comment]
> Daxx, you should be fixed now. Garyking, if you send me your HN username I can forward it to HN API admin to fix. They said otherwise you need to post or comment to work.

My username is GaryKing, please help me fix that, thanks.

**Comment by Daxx909** [comment]
Works now, thanks!

**Comment by garyking** [comment]
Mine works too now.
