### ISSUE TITLE
App gets stuck when using Safari in-app

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#85]
If you navigate to this post on AskHN: [Anyone else frustrated with current macOS file manager solutions?](https://news.ycombinator.com/item?id=20020596) and then scroll to [this comment](https://news.ycombinator.com/item?id=20021484) you'll see a link to https://fman.io/ 

Clicking that link takes you to the landing page, which contains some kind of autoplaying video. The problem is, as soon as you start to scroll that page, the video goes full screen and gets stuck just playing a short loop of a rocket being loaded with fuel.

I couldn't find any way out of this other than force-quitting the app. Not sure if there is any way to fix this from Octal's side or if it's just a Safari bug. In "regular" Safari, at least I am able to pinch to close the video, but that doesn't work inside Octal.

Thanks

**Comment by dangwu** [comment]
Wow, weird bug, and I assume it is on SafariViewController's side. In normal Safari I was able to single tap to bring up the video controls and exit. In Octal, I could only swipe back to exit the view entirely. I'm not doing anything special on Octal's side - just presenting an SFSafariViewController instance.

**Comment by dangwu** [comment]
Closing this, as there's nothing I can really do here. At least we can swipe back to exit the web browser.
