### ISSUE TITLE
[Feature] Long press on 'jump to next comment thread' button should go to previous one

### ISSUE THREAD

**Issue by garyking** [dangwu/Octal#87]
Pressing on the down arrow goes to the next comment thread. Please make it possible to press and hold on the down arrow, to go back up to the previous comment thread.

This is a feature that exists in the Apollo app for Reddit, as an example.

**Comment by dangwu** [comment]
Nice idea! Adding to my TODO list.

**Comment by dangwu** [comment]
This is now available in 4.4.1!
