### ISSUE TITLE
[Bug] 'Jump to next comment thread' button doesn't correctly focus the first comment thread

### ISSUE THREAD

**Issue by garyking** [dangwu/Octal#88]
There's a down arrow that goes to the next comment thread each time it's pressed.

When opening a story, after pressing it once, the page scrolls down to the post thumbnail. Pressing it again scrolls to the second comment thread. The first comment thread therefore never gets focused.

Why does it even bother focusing on the thumbnail the first time? The only reason that would seem to be necessary, is if the headline is so long that it pushes the thumbnail too far down, which seems very rare. Why not instead focus on the first comment thread, upon the first press of the down arrow button?

**Comment by dangwu** [comment]
Weird, it's supposed to focus the first comment thread. I'll look into it. I never noticed this because I usually just scroll to the first comment thread.

**Comment by dangwu** [comment]
This has been fixed
