### ISSUE TITLE
Make it possible to save a post on the post list

### ISSUE THREAD

**Issue by garyking** [dangwu/Octal#89]
On the list of posts, in addition to being able to upvote a post with a swipe, please make it possible to save a post by swiping in the other direction, to add a post to our favorites.

**Comment by dangwu** [comment]
Good idea - will do

**Comment by dangwu** [comment]
Added swipe to add to favorites option.

**Comment by garyking** [comment]
I just noticed that HN doesn't have a favorites API endpoint. Are you just scraping the favorites page, and the favorite/unfavorite buttons, to get that functionality in the app?

**Comment by dangwu** [comment]
Correct
