### ISSUE TITLE
[Feature] mark comments as read

### ISSUE THREAD

**Issue by YayC** [dangwu/Octal#91]
On another hn reader, the article + comments were marked as read after viewing comments. Unless I’m missing something, the only rows marked as read in octal are those where you open the article itself.

I miss the other behavior, since I usually don’t open the article link and it made it easy to see which threads I had already visited.

**Comment by dangwu** [comment]
I'll add this as an option. I know some people prefer it the way it is.

**Comment by YayC** [comment]
Thank you, that would be great!! An alternative would be to mark comments as read separately in the UI (which could be even better if done well). But an option to mark the submission as read after viewing comments works well for my use-case

**Comment by dangwu** [comment]
Added in 3.16.0
