### ISSUE TITLE
Stutters in comment scrolling

### ISSUE THREAD

**Issue by HarshdeepKahlon** [dangwu/Octal#93]
I'm using Octal 3.80 with iOS 12.3.1 on my iPhone X. When slowly scrolling in any comment section, there is frequent stutter. It might be hard to see in this [video](https://streamable.com/6jcoc), but it's there. Thanks!

**Comment by dangwu** [comment]
Thanks - I’m aware of the new micro stuttering. I had to remove comment preloading code (NSAttributedString-related) because I believe it was causing rare a comment freezing issue. I’ll work on making it smoother again soon!

**Comment by dangwu** [comment]
Should be silky smooth again in 3.8.1. Let me know if not!

**Comment by sammoth** [comment]
I am still experiencing microstutter on 3.8.2 in the comment section, and a little bit on the homepage too, though I’m not sure how bad it is compared to before.
