### ISSUE TITLE
[Feature] Add downvote

### ISSUE THREAD

**Issue by vpark** [dangwu/Octal#95]
Hey first of all, loving the app. I wanted to ask for a downvote feature on the app. Right now there are various ways to customize left and right swipes.

It’d be great if downvote was also possibly with the gesture (or some other method altogether).

Also just wanted to let you know that my account definitely does have downvote enabled so it’s not an issue with my account being too new or anything on HN.

**Comment by dangwu** [comment]
Hi! I'd like to add downvote, but my HN account doesn't have the feature yet, and I need access to replicate the API calls within Octal... I'll try to post more. Stay tuned.

**Comment by jxcl** [comment]
Maybe this would be helpful?

Downvote request:
```
GET https://news.ycombinator.com/vote?id=21203422&how=down&auth=<snip>&goto=item%3Fid%3D21202905#21203422
[HTTP/1.1 302 Moved 163ms]

	
Query string	
id	21203422
how	down
auth	<snip>
goto	item?id=21202905```

Undown request:
```
GEThttps://news.ycombinator.com/vote?id=21203422&how=un&auth=<snip>&goto=item%3Fid%3D21202905#21203422
[HTTP/1.1 302 Moved 75ms]

	
Query string	
id	21203422
how	un
auth	<snip>
goto	item?id=21202905
```

**Comment by dangwu** [comment]
@Alexander Bliskovsky

This is super helpful - exactly what I needed. Thank you!

**Comment by dangwu** [comment]
Is anyone willing to test upvote/downvote for me? I can provide a TestFlight build in the future!

**Comment by dangwu** [comment]
I've added downvoting comments to 3.34.0, released moments ago!
