### ISSUE TITLE
Give me back my real iOS keyboard

### ISSUE THREAD

**Issue by bknowles** [dangwu/Octal#96]
Let me use shift or caps lock to type in ALL CAPS, like I can do here.

Don’t make me hold down the shift key while typing, in order to get that functionality.

Also please remove about 200ms of unnecessary additional delay when typing characters. Typing on iOS should be virtually instaneous, and in Octal, that is no longer true.

**Comment by dangwu** [comment]
I’m not experiencing any of these issues. Can you share a video example?

**Comment by bknowles** [comment]
> I’m not experiencing any of these issues. Can you share a video example?

That will take some work to set up.  And it won't show what I'm forced to do with my fingers versus what is shown on screen.

But I do have the tools necessary to do a video capture of the UI from my iPad, using Screenflow.

And for what I'm forced to do with my fingers at the iOS keyboard, I guess I could set up my iPhone on a tripod or something and take a video showing what the input looks like for the Screenflow session.

Let me work on that.

**Comment by dangwu** [comment]
Closing. Feel free to reopen if you repro with video.
