### ISSUE TITLE
[Bug] Share button from comment page not passing Page Title

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#98]
I often save interesting HN links to Pinbord for reading later. The app I use is [Pushpin](https://apps.apple.com/us/app/pushpin-for-pinboard/id548052590).

When saving links from the comment page, it seems only the URL is passed, so the Title ends up being blank and I have to swipe to get Pushpin to fetch the title, or type something by hand.

I know the share sheet is "capable" of passing a Title + URL because some other HN apps do it, e.g. [HACK](https://apps.apple.com/us/app/hack-for-hacker-news-developer/id1464477788) or [MiniHack](https://apps.apple.com/us/app/minihack/id631108846)

Is this enhancement possible?

**Comment by luckman212** [comment]
_Some screenshots to help illustrate:_

A story shared from Octal (note the missing Title):
![IMG_9978_33](https://user-images.githubusercontent.com/1992842/63228028-558f2380-c1bb-11e9-9daf-618b05c26354.jpg)

Same story shared from HACK:
![IMG_9979_33](https://user-images.githubusercontent.com/1992842/63228029-558f2380-c1bb-11e9-87cd-6512907022af.jpg)

Animation of the share sheet being triggered from HACK, showing both Title & URL being passed:
![9980](https://user-images.githubusercontent.com/1992842/63228033-68095d00-c1bb-11e9-907b-28aa6741e084.png)

**Comment by dangwu** [comment]
This is very possible. I'll add it soon™. Sorry for the late response - been very busy!

**Comment by luckman212** [comment]
Cool, thank you for looking at it!

**Comment by dangwu** [comment]
v3.8.3 *should* fix this. I don't have Pushpin, but I tested with the stock Mail app and the subject is now included. Should be out tomorrow at the latest!

**Comment by luckman212** [comment]
I am sorry to seem ungrateful -- but the titles are still not populating in Pushpin.

I think I discovered the problem. When other apps e.g. Hack are passing data to the share sheet, there is a URL component as well as a Text component. (See screenshot below)

But Octal is only passing the URL component (according to Anybuffer: https://apps.apple.com/us/app/anybuffer/id1330815414)

**Comment by dangwu** [comment]
Gotcha. I can add the title with every share.

**Comment by dangwu** [comment]
v3.9.0 is out now and passes the title with every share

**Comment by luckman212** [comment]
Ok now this is getting really weird! I have 3.9.0 and can confirm that Octal is passing the plain txt component to the share sheet. It "looks" like the same content from Hack vs Octal when viewed in Anybuffer. But, for some reason, shares from Octal _still_ are not appearing with the title set. There must be some other flag or data type declaration that is slightly different here. Very odd.

**Comment by dangwu** [comment]
Ah, that sucks! I'll keep investing when I get time.

**Comment by luckman212** [comment]
I'm not sure. But when I look at the outputs from both apps in Anybuffer, they look the same. HACK also creates 2 objects (a `public.url` and a `public.plain-text`).  Maybe the URL component also contains the title somehow. It's hard for me to tell, but the # of bytes is different between the public.URL component created by HACK vs Octal, so maybe that's it. When I checked, the output from HACK was substantially _fewer_ bytes - which is surprising.

**Comment by luckman212** [comment]
_Ok, a bit more on this:_ I cobbled together 2 custom Shortcuts for iOS (I created them on iOS13 but I think they work on iOS12 as well). These might help in debugging. Download them from the iCloud links below:

1. [Inspect](https://www.icloud.com/shortcuts/837486d0d05b41398d4b83d8a380edb0)
2. [View Elements](https://www.icloud.com/shortcuts/90e27beee4ae40c1b08abdc2992b868a)

Make sure "Show in Share Sheet" is enabled after importing so they appear:
![image](https://user-images.githubusercontent.com/1992842/65350022-c490db00-dbb2-11e9-9a3f-81adba9da3c8.png)

![image](https://user-images.githubusercontent.com/1992842/65349973-a9be6680-dbb2-11e9-8e53-927dafdf7003.png)

The **Inspect** Shortcut just loops thru the passed elements, saving the datatypes to a variable and displaying them at the end, e.g: for this HN link [Amazon orders 100K electric delivery trucks from Rivian](https://news.ycombinator.com/item?id=21017448), here's the output from HACK:
![image](https://user-images.githubusercontent.com/1992842/65350137-0457c280-dbb3-11e9-94a2-ce5124ac25d6.png)

**View Elements** is even simpler and just uses a "Choose from List" UI picker to present the elements passed from the sharesheet. Conveniently, it also shows the datatype below each item. 

Using that, I noticed that the "Type" is not set by Octal (defaults to "Text" in that case). However HACK and other apps do pass explicit datatypes for each component (Text, URL).

![image](https://user-images.githubusercontent.com/1992842/65350250-47b23100-dbb3-11e9-88ea-f290d2b3ca9b.png)
_(output from HACK)_

![image](https://user-images.githubusercontent.com/1992842/65350391-9f509c80-dbb3-11e9-911a-6aee9b120adb.png)
_(output from Octal, same article)_

I think this is the key difference!

**Comment by dangwu** [comment]
Nice investigation! Why does Octal not show any type at all? I thought it would default to Text?

Regardless, I am currently only sharing the String of the URL instead of an actual URL object, so that definitely sounds like it would be the fix! I’ll get on it soon.

**Comment by dangwu** [comment]
Have you tried the latest release? Should hopefully be fixed.

**Comment by dangwu** [comment]
Hopefully fixed in 3.10.0 coming soon!

**Comment by dangwu** [comment]
How’s it looking with 3.10.0?

**Comment by luckman212** [comment]
3.10.0 just appeared for me this morning. It's working! Thank you again for sticking with this one!
