### ISSUE TITLE
Toggle Infinite Scroll

### ISSUE THREAD

**Issue by josephwegner** [dangwu/Octal#99]
One of the things I like about the actual HN website is that it only shows a handful of articles at a time. This is valuable to me for two reasons:

1. It tile boxes the amount of time I can waste on HN
2. It is a sort of “quality indicator”. Articles that reach front page status are generally better than those that don’t. 

I understand the desire for infinite scroll, and imagine people would be pissed if it was removed altogether, but I would greatly appreciate the ability to toggle it. Or perhaps have a filter option like “Top N”. This is most certainly something so would pay for as a Premium feature.

**Comment by dangwu** [comment]
In 3.9.0 I've added a Limit option to the filter, to only fetch/display the top N. Thanks for the idea!
